### ISSUE TITLE
Allow reading the log of a pod

### ISSUE THREAD

**Issue by dasch** [abonas/kubeclient#119]
There's an endpoint for it: http://kubernetes.io/v1.0/docs/api-reference/operations.html#_read_log_of_the_specified_pod

I can't figure out how to use kubeclient to do it, though.

**Comment by abonas** [comment]
Hi @dasch , thanks for bringing this up. Kubeclient doesn't support this feature yet. Contributions are welcome :)
cc @simon3z

**Comment by simon3z** [comment]
The kubernetes side is lacking of a couple features that I'd need to make the log collection really usable for my use-case. Which means that for me at this time the kubeclient side is not interesting yet. But obviously if there's a contribution we'll gladly accept it.

**Comment by jimmidyson** [comment]
@simon3z Out of interest, what log functionality do you think is lacking in Kubernetes? There's an open issue (kubernetes/kubernetes#12447) to collect some ideas to make log endpoint more useful - good to hear your thoughts there if you have ideas.

**Comment by jonmoter** [comment]
@abonas, I was looking at the code to implement this functionality.  The way that `Kubeclient::Client` is implemented, it seems pretty straightforward to have CRUD-like functionality for the main objects, like Services, Pods, Events, etc.

But log retrieval uses an endpoint of the form `GET /api/v1/namespaces/{namespace}/pods/{name}/log`, which is an endpoint that is specific to the Pod object.  I don't see an elegant way of adding functionality specific to one of the objects that's not in the others.

Do you have a plan/design in mind for how to add that sort of functionality?  Or should I come up with something that seems sane to me, and we can hash out the details in a pull request?

**Comment by abonas** [comment]
@jonmoter Hi, I didn't think yet how to implement it, and I'd like to hear first @simon3z which log functionality he is looking for in k8s. 
Generally speaking, the client doesn't have to mimic the way the server api is structured. And the objects themselves that are constructed on client side (pod, etc.) have only data, not logic such as going to server again - I think it's better to keep them clean from server connections, etc. 
Hence, in theory, you could have something like client.get_log (namespace, pod_name) , but this is really a brief thought on the topic.

**Comment by jonmoter** [comment]
@abonas PR #121 is my first pass at implementing functionality to get (or watch) logs from a pod. The Kubernetes API doesn't expose any more functionality than what I've implemented.  So that's all we can do for now.
