### ISSUE TITLE
Parse Kubernetes config file to create clients

### ISSUE THREAD

**Issue by jonmoter** [abonas/kubeclient#122]
When you run the Kubernetes installer on Vagrant, it creates a YAML file for you in your home directory called `~/.kube/config`, that contains the same information if you ran `kube config view`.  For example:

```
$ kubectl config view
apiVersion: v1
clusters:
- cluster:
    server: http://127.0.0.1:9999
  name: kubepoc
- cluster:
    certificate-authority-data: REDACTED
    server: https://10.245.1.2
  name: vagrant
contexts:
- context:
    cluster: kubepoc
    user: ""
  name: kubepoc
- context:
    cluster: vagrant
    user: vagrant
  name: vagrant
current-context: vagrant
kind: Config
preferences: {}
users:
- name: vagrant
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
    password: vagrant
    username: vagrant
```

For a project I'm working on, I wrote up a class that parses that config file and can construct a `Kubeclient::Client` based on that information.  For example:

```ruby
config = ClientConfigFile.new(ENV['HOME'] + '/.kube/config')
client = config.client_for('vagrant')
client.get_pods
```

Would you like me to open up a PR that contains that code?  I figure it would be something generally useful for people using this gem.

**Comment by abonas** [comment]
@jonmoter, my preference at this point is not to contain such configuration and parsing as part of the client.
There are several different ways to configure kubernetes, and by adding them here,  they will need maintenance and support as part of the client, and I would like at this point to avoid it.

**Comment by jonmoter** [comment]
Okay, fair enough.
