### ISSUE TITLE
Allow watching events with a labelSelector

### ISSUE THREAD

**Issue by jonmoter** [abonas/kubeclient#123]
I want to be able to subscribe to watch events for pods that match a label selector, which is supported by the Kubernetes API, but not the client gem.

e.g. you can make a call to `/api/v1/watch/pods?labelSelector=foo%3Dbar` to get events for all pods that match the selector "foo=bar".

I'd like to add an `options` hash to `#watch_entities`, allowing you to pass in optional values for the labelSelector and fieldSelector parameters that the API accepts.

**Comment by abonas** [comment]
@jonmoter thanks for the idea, need to see how much work it is to add it since this was not on the near future roadmap.
cc @simon3z

**Comment by jonmoter** [comment]
I have some code working locally, so I could open up a PR for review.

**Comment by abonas** [comment]
> I have some code working locally, so I could open up a PR for review.

Contributions are welcome.
please note that me and the other maintainer of the client are very partially available during the next 2 weeks, so some response/review delays are expected.
