### ISSUE TITLE
Watcher crashes when WatchStream#finish called during event processing

### ISSUE THREAD

**Issue by msufa** [abonas/kubeclient#139]
### Use case:
- set up a pod watcher (Kubeclient::Client#watch_pods)
- in the block passed to WatchStream#each, based on some condition (e.g. N/N pods ready), decide to stop watching pods
- call WatchStream#finish

### Result:
The client crashes with:
```
2.2.3/lib/ruby/2.2.0/net/http.rb:1452:in `begin_transport': undefined method `closed?' for nil:NilClass (NoMethodError)
2.2.3/lib/ruby/2.2.0/net/http.rb:1410:in `transport_request'
2.2.3/lib/ruby/2.2.0/net/http.rb:1384:in `request'
2.2.3/lib/ruby/gems/2.2.0/gems/rack-mini-profiler-0.9.7/lib/patches/net_patches.rb:7:in `block in request_with_mini_profiler'
2.2.3/lib/ruby/gems/2.2.0/gems/rack-mini-profiler-0.9.7/lib/mini_profiler/profiling_methods.rb:38:in `step'
2.2.3/lib/ruby/gems/2.2.0/gems/rack-mini-profiler-0.9.7/lib/patches/net_patches.rb:6:in `request_with_mini_profiler'
2.2.3/lib/ruby/gems/2.2.0/bundler/gems/kubeclient-9bbfbd7e8f5f/lib/kubeclient/watch_stream.rb:21:in `each'
```

My best guess is that after calling WatchStream#finish the socket is set to nil, but the watcher is still trying to read in event data.

A simple fix in WatchStream#each seemed to resolve the issue:
```
diff --git a/lib/kubeclient/watch_stream.rb b/lib/kubeclient/watch_stream.rb
index 1e0a880..81356e1 100644
--- a/lib/kubeclient/watch_stream.rb
+++ b/lib/kubeclient/watch_stream.rb
@@ -26,6 +26,7 @@ module Kubeclient
             buffer << chunk
             while (line = buffer.slice!(/.+\n/))
               yield @format == :json ? WatchNotice.new(JSON.parse(line)) : line.chomp
+              return if @finished
             end
           end
         end
```

I'm not sure if it's me misusing the client, or if there in fact is a problem. I'm also not sure if this trivial fix is entirely safe. I would appreciate any comments.

**Comment by abonas** [comment]
@msufa thanks for the report, @simon3z please review / comment

**Comment by simon3z** [comment]
@msufa you haven't posted your code but calling `finish` inside the each block is not safe. You should do something like

    watcher.each do |x|
      ...
      break if my_condition
    end

    watcher.finish

**Comment by msufa** [comment]
Thanks @simon3z! I tried it following your suggestion and everything works fine now. I don't see any crashes on WatchStream#finish. Closing the issue.

**Comment by jonmoter** [comment]
This would probably be a good thing to document in the README and/or in the code somewhere.
