### ISSUE TITLE
Use a non-blocking HTTP library

### ISSUE THREAD

**Issue by msufa** [abonas/kubeclient#140]
We have found that using `WatchStream`s inside `Celluloid` actors is a perfect fit for a background event watcher. The only problem is that `net/http` is incompatible with `Celluloid::IO` and it blocks the actor on reading the response, making it impossible to manage. Have you considered using a non-blocking HTTP library, like https://github.com/httprb/http ? We have successfully used it in a monkey patch of the `WatchStream` inside our own project which is using `kubeclient`: https://github.com/zendesk/samson/blob/msufa/cluster_pod_watcher/plugins/kubernetes/config/initializers/watchers.rb

I would appreciate your comments.

**Comment by simon3z** [comment]
> I would appreciate your comments.

@msufa in the past I've considered several libraries, as `typhoeus`, `em-http-request`, `curl-multi`, etc. but they all had at least one problem that we couldn't address.

Off the top of my head requirements are:

- support basic authentication
- support specific headers
- support ssl (verify mode, client certificate, cert store etc.)
- long-standing connection (no timeout, events may come in rarely)
- read the body as a stream (don't wait for the end of the body)
- ability to cleanly close the connection (e.g. from another thread)

If you verified that all these are supported then I can start testing your changes and we'll take it from there. Thanks!

**Comment by msufa** [comment]
@simon3z I did not perform any testing, but I had a closer look at the gem and found that:
 - support basic authentication
  - it supports user/password & bearer authentication
 - support specific headers
  - check
 - support ssl (verify mode, client certificate, cert store etc.)
  - it consumes `OpenSSL::SSL::SSLContext` so I assume it supports everything you can stuff in there
 - long-standing connection (no timeout, events may come in rarely)
  - it does not time out by default
 - read the body as a stream (don't wait for the end of the body)
  - check, I'm actually using this in my monkey patch
 - ability to cleanly close the connection (e.g. from another thread)
  - I'm using it through `Celluloid` actors and haven't bumped into problems closing connections yet

**Comment by simon3z** [comment]
> @simon3z I did not perform any testing, but I had a closer look at the gem and found that:

Send a PR and I'll test it to check if there was anything else that I forgot. Thanks.

**Comment by msufa** [comment]
It took me a while but the PR to resolve this is finally published. Please review #142 @simon3z

**Comment by henders** [comment]
Nice! +1

**Comment by msufa** [comment]
The relevant PR has been merged so I consider the issue closed. Thanks @simon3z & @abonas for handling that!
