### ISSUE TITLE
Support new group API

### ISSUE THREAD

**Issue by simon3z** [abonas/kubeclient#144]
Kubernetes documentation:

- http://kubernetes.io/v1.1/docs/proposals/api-group.html#server-side-implementation

following the kubernetes description the entities can be reached using the `prefix`, `group` and `version` values.

- for `/api/v1`, we set the `prefix="api"`, `group=""`, `version="v1"`, so the URL remains to be `/api/v1`

A similar approach (client-side) could be used in kubeclient.

- `prefix` and `group` should be preconfigured per-entity (e.g. for all current entities should be `prefix="api"`, `group=""`)
- `version` should be more easily configurable per request

For example:

    client.get_pods
    # prefix="api", group="", version="v1"
    # => /api/v1/pods

For group api (e.g. deployments) we could use just a plain form in the API:

- `client.get_deployments`

but I believe that it would be better to scope them in some way:

- `client.extensions.get_deployments`
- `client.extensions_get_deployments`

and for example:

    client.extensions.get_deployments
    # prefix="apis", group="extensions", version="v1beta1"
    # => /apis/extensions/v1beta1/depoyments

**Comment by simon3z** [comment]
cc @abonas @jimmidyson @msufa @jonmoter

**Comment by henders** [comment]
I see, so you could represent all the entity types like?
```ruby
ENTITY_TYPES = {
  Pod: { prefix: 'api', group: nil, version: 'v1' },
  ReplicationController: { prefix: 'api', group: nil, version: 'v1' },
  Service: { prefix: 'api', group: nil, version: 'v1' },
  Deployment: { prefix: 'apis', group: 'extensions', version: 'v1beta1' },
  ...
}

**Comment by abonas** [comment]
IMO hardcoding entity types in the client like we do today, whether it is done with group/api version or without, is not the optimal design approach.
What I would like to see, is the ability to query the server for api versions and the entity types supported in each api version - because the server "knows best" what does it support. That will allow the flexibility needed and will reduce the number of hardcoded things in the client. @thockin, your thoughts on the topic?

**Comment by henders** [comment]
I'd +1 to that idea of loading the supported APIs from K8s.

In a Rails app, the user could call a method in an initializer to cause Kubeclient to connect to K8s to interrogate K8s over which APIs it supports.
Further advantages is auto-creating methods like ```client.pods.log``` or ```client.pods.exec``` as K8s returns these more specific resource methods in that API list as well:
```
➜  samson git:(shender/k8s_deployment_api) ✗ curl -XGET http://localhost:8080/api/v1
{
  "kind": "APIResourceList",
  "groupVersion": "v1",
  "resources": [
  {
      "name": "namespaces",
      "namespaced": false
    },
    {
      "name": "pods",
      "namespaced": true
    },
    {
      "name": "pods/exec",
      "namespaced": true
    },
    {
      "name": "pods/log",
      "namespaced": true
    },
    {
      "name": "replicationcontrollers",
      "namespaced": true
    },
...
<snip>
...
  ]
}
```

**Comment by abonas** [comment]
@henders, we do have today the methods api and api_valid? that fetch the version numbers that the server supports, so the direction I'd like to see is extending that approach to get more info on each version from the server.

**Comment by thockin** [comment]
@nikhiljindal I thought we had something like this, but I can't recall the details (haven't used it much, obv)

**Comment by nikhiljindal** [comment]
Yes, API server exposes a "discovery API" as explained in "supporting API discovery" point in that doc http://kubernetes.io/v1.1/docs/proposals/api-group.html#server-side-implementation.

Clients can discover the groups exposed by the server, list of versions supported by each group including the preferred version, and the list of resources in each group version.

We also plan to refactor our clients as per https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/client-package-structure.md
We plan to have typed clients bound to specific groupVersions that will support interface like client.Pods() and a dynamic client, that can discover the resources exposed by server using the discovery API and work with any resource.

cc @kubernetes/goog-csi

**Comment by caesarxuchao** [comment]
PR that adds the server-side support for discovery: https://github.com/kubernetes/kubernetes/pull/13955#issuecomment-141157000

The golang discovery-client: https://github.com/kubernetes/kubernetes/blob/master/pkg/client/unversioned/discovery_client.go
It simply visits the discovery path and decode the results, it's not a dynamic client.

**Comment by jonmoter** [comment]
Is there any movement on this issue?  Would you like a proposal or a PR?

I ask 'cause we're using both Deployments and DaemonSets in our integration, and we're monkey-patching kubeclient to support those. @henders opened PR #143 several months ago, but that appears to be in PR purgatory.

**Comment by simon3z** [comment]
@moolitayer can you take a look at this issue?

In general I think it's critical that we'll move to the group api in the upcoming months. As mentioned in a previous [comment](https://github.com/abonas/kubeclient/issues/144#issuecomment-165308499) we can leverage the API discovery:

https://github.com/kubernetes/kubernetes/blob/release-1.2/docs/proposals/api-group.md#server-side-implementation

There may even be a convergence with `openshift_client` as OpenShift may be seen as just another group/plugin (I think the API was designed with that in mind).

cc @deads2k

**Comment by deads2k** [comment]
> There may even be a convergence with openshift_client as OpenShift may be seen as just another group/plugin (I think the API was designed with that in mind).

That's a long term goal, but I don't think we'll be there for 1.3.  I will make it a point to experiment with at least one of our logical groups this release, but I doubt we'll be able to contain migrating all of them.

**Comment by erez-rabih** [comment]
Hi,
Just bumped into this issue as we're using the deployments API extensively and would like to use the ruby client with it.
I can create a PR if needed.

**Comment by quavmo** [comment]
Really grateful for the work this library has allowed me to do, and I'm definitely interested in reviewing a PR that makes `Kubeclient::Client#foo_ingress` possible. @erez-rabih, how motivated are you to create a PR enabling the group API?

**Comment by simon3z** [comment]
> Really grateful for the work this library has allowed me to do, and I'm definitely interested in reviewing a PR that makes Kubeclient::Client#foo_ingress possible. @erez-rabih, how motivated are you to create a PR enabling the group API?

@quavmo please keep in contact with @moolitayer. He's probably going to start some work on this any time soon.

**Comment by moolitayer** [comment]
@simon3z @quavmo @erez-rabih I'm working on this and should have an update soon

**Comment by erez-rabih** [comment]
@moolitayer Thanks for the update, much appreciated.

**Comment by moolitayer** [comment]
# Specification for groups & auto discovery support

Currently we support arguments for the api path and version and guess '/api' and 'v1' if not provided.
Both of these are valid today and create a client for the same endpoint:
```
client = Kubeclient::Client.new('http://localhost:8080/api' , 'v1')
client = Kubeclient::Client.new('http://localhost:8080' )
```

We will continue to support both.
It will be possible to create a client for the groups api:
```
client = Kubeclient::Client.new('http://localhost:8080/apis' , 'v1')
```

## Api versions
The client will continue to be created with and have a specific version.
A default 'v1' is already provided for the core api ('/api'). 
The group api will have no default version.

## Discovery
After examining the problem and writing discovery code I do not see the benefit in discovering groups and resources by parsing APIGroupList[3] and APIResourceLists[4].
The reason in whether we do discovery or not, a user calling a method on a non existing resource or a not allowed method (e.g get for api/binding) will both fail at runtime. The only benifit we do get is in code completion.

I suggest is to drop kubeclient's method completion.

When we have a core client ('/api') that calls a method:
```
client.get_pods # the client should attempt a get /api/version/pods
```
When we have a groups client ('/apis') that calls a method:
```
client.autoscaling.get_horizontal_pod_autoscalers # the client should attempt a get on /apis/autoscaling/version
```

## Nested Resources
Looking at [4] we can see the nested resources of 'pods':
/pods
/pods/name/status
/pods/name/logs
and others
Nested resources will be available with a suffix to an existing resource
```
client.get_pods(nested = 'status')
```
We aim to provide backward compatibility to existing methods for nested resources i.e 'get_pod_log' and 'watch_pod_log'

## First level resources
First level resources[5] should be available in both core and group clients. They will be provided statically per need 

## Relevant Resources
[1] http://kubernetes.io/docs/api/
[2] https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/api-group.md
[3]
APIGroupList
/apis

```
{
  "kind": "APIGroupList",
  "groups": [
    {
      "name": "apps",
      "versions": [
        {
          "groupVersion": "apps/v1alpha1",
          "version": "v1alpha1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "apps/v1alpha1",
        "version": "v1alpha1"
      },
      "serverAddressByClientCIDRs": [
        {
          "clientCIDR": "0.0.0.0/0",
          "serverAddress": "10.35.2.174:6443"
        }
      ]
    },
    {
      "name": "autoscaling",
      "versions": [
        {
          "groupVersion": "autoscaling/v1",
          "version": "v1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "autoscaling/v1",
        "version": "v1"
      },
      "serverAddressByClientCIDRs": [
        {
          "clientCIDR": "0.0.0.0/0",
          "serverAddress": "10.35.2.174:6443"
        }
      ]
    },
    {
      "name": "batch",
      "versions": [
        {
          "groupVersion": "batch/v1",
          "version": "v1"
        },
        {
          "groupVersion": "batch/v2alpha1",
          "version": "v2alpha1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "batch/v1",
        "version": "v1"
      },
      "serverAddressByClientCIDRs": [
        {
          "clientCIDR": "0.0.0.0/0",
          "serverAddress": "10.35.2.174:6443"
        }
      ]
    },
    {
      "name": "certificates",
      "versions": [
        {
          "groupVersion": "certificates/v1alpha1",
          "version": "v1alpha1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "certificates/v1alpha1",
        "version": "v1alpha1"
      },
      "serverAddressByClientCIDRs": [
        {
          "clientCIDR": "0.0.0.0/0",
          "serverAddress": "10.35.2.174:6443"
        }
      ]
    },
    {
      "name": "extensions",
      "versions": [
        {
          "groupVersion": "extensions/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "extensions/v1beta1",
        "version": "v1beta1"
      },
      "serverAddressByClientCIDRs": [
        {
          "clientCIDR": "0.0.0.0/0",
          "serverAddress": "10.35.2.174:6443"
        }
      ]
    },
    {
      "name": "policy",
      "versions": [
        {
          "groupVersion": "policy/v1alpha1",
          "version": "v1alpha1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "policy/v1alpha1",
        "version": "v1alpha1"
      },
      "serverAddressByClientCIDRs": [
        {
          "clientCIDR": "0.0.0.0/0",
          "serverAddress": "10.35.2.174:6443"
        }
      ]
    },
    {
      "name": "rbac.authorization.k8s.io",
      "versions": [
        {
          "groupVersion": "rbac.authorization.k8s.io/v1alpha1",
          "version": "v1alpha1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "rbac.authorization.k8s.io/v1alpha1",
        "version": "v1alpha1"
      },
      "serverAddressByClientCIDRs": [
        {
          "clientCIDR": "0.0.0.0/0",
          "serverAddress": "10.35.2.174:6443"
        }
      ]
    }
  ]
}
```
[4]
APIResourceLists
/api/version
/apis/GROUP/VERSION (e.g /apis/autoscaling/v1)
```
{
  "kind": "APIResourceList",
  "groupVersion": "v1",
  "resources": [
    {
      "name": "bindings",
      "namespaced": true,
      "kind": "Binding"
    },
    {
      "name": "componentstatuses",
      "namespaced": false,
      "kind": "ComponentStatus"
    },
    {
      "name": "configmaps",
      "namespaced": true,
      "kind": "ConfigMap"
    },
    {
      "name": "endpoints",
      "namespaced": true,
      "kind": "Endpoints"
    },
    {
      "name": "events",
      "namespaced": true,
      "kind": "Event"
    },
    {
      "name": "limitranges",
      "namespaced": true,
      "kind": "LimitRange"
    },
    {
      "name": "namespaces",
      "namespaced": false,
      "kind": "Namespace"
    },
    {
      "name": "namespaces/finalize",
      "namespaced": false,
      "kind": "Namespace"
    },
    {
      "name": "namespaces/status",
      "namespaced": false,
      "kind": "Namespace"
    },
    {
      "name": "nodes",
      "namespaced": false,
      "kind": "Node"
    },
    {
      "name": "nodes/proxy",
      "namespaced": false,
      "kind": "Node"
    },
    {
      "name": "nodes/status",
      "namespaced": false,
      "kind": "Node"
    },
    {
      "name": "persistentvolumeclaims",
      "namespaced": true,
      "kind": "PersistentVolumeClaim"
    },
    {
      "name": "persistentvolumeclaims/status",
      "namespaced": true,
      "kind": "PersistentVolumeClaim"
    },
    {
      "name": "persistentvolumes",
      "namespaced": false,
      "kind": "PersistentVolume"
    },
    {
      "name": "persistentvolumes/status",
      "namespaced": false,
      "kind": "PersistentVolume"
    },
    {
      "name": "pods",
      "namespaced": true,
      "kind": "Pod"
    },
    {
      "name": "pods/attach",
      "namespaced": true,
      "kind": "Pod"
    },
    {
      "name": "pods/binding",
      "namespaced": true,
      "kind": "Binding"
    },
    {
      "name": "pods/exec",
      "namespaced": true,
      "kind": "Pod"
    },
    {
      "name": "pods/log",
      "namespaced": true,
      "kind": "Pod"
    },
    {
      "name": "pods/portforward",
      "namespaced": true,
      "kind": "Pod"
    },
    {
      "name": "pods/proxy",
      "namespaced": true,
      "kind": "Pod"
    },
    {
      "name": "pods/status",
      "namespaced": true,
      "kind": "Pod"
    },
    {
      "name": "podtemplates",
      "namespaced": true,
      "kind": "PodTemplate"
    },
    {
      "name": "replicationcontrollers",
      "namespaced": true,
      "kind": "ReplicationController"
    },
    {
      "name": "replicationcontrollers/scale",
      "namespaced": true,
      "kind": "Scale"
    },
    {
      "name": "replicationcontrollers/status",
      "namespaced": true,
      "kind": "ReplicationController"
    },
    {
      "name": "resourcequotas",
      "namespaced": true,
      "kind": "ResourceQuota"
    },
    {
      "name": "resourcequotas/status",
      "namespaced": true,
      "kind": "ResourceQuota"
    },
    {
      "name": "secrets",
      "namespaced": true,
      "kind": "Secret"
    },
    {
      "name": "serviceaccounts",
      "namespaced": true,
      "kind": "ServiceAccount"
    },
    {
      "name": "services",
      "namespaced": true,
      "kind": "Service"
    },
    {
      "name": "services/proxy",
      "namespaced": true,
      "kind": "Service"
    },
    {
      "name": "services/status",
      "namespaced": true,
      "kind": "Service"
    }
  ]
}
```
[5]
First Level Resources currently available
```
 "/healthz",
 "/healthz/ping",
 "/logs/",
 "/metrics",
 "/swaggerapi/",
 "/ui/",
 "/version"
```
