### ISSUE TITLE
Current release (0.9.0) doesn't work on ruby 2.3.x

### ISSUE THREAD

**Issue by bkoski** [abonas/kubeclient#149]
The build currently available on rubygems doesn't include this commit:
https://github.com/abonas/kubeclient/commit/eea106035141c896803325000fd4bf00da369521

and so depends on recusive_open_struct 0.6.1.  It seems 0.6.1 doesn't work on ruby 2.3.0; nested objects are returned as Hashes rather than OpenStructs.

Was able to work around this for now by installing the gem directly from github, but would it be possible to release a new version with this patch?

**Comment by simon3z** [comment]
@abonas are we planning a build soon? Supporting ruby 2.3 seems important enough but IIRC there's some problem with testing it on travis (it shouldn't block the release though). Other than that there's no much more meat since 0.9.0 at the moment.

**Comment by abonas** [comment]
@bkoski I just released 1.0.0 to contain the ROS version 1.0 support, as well as the travis config to work with 2.3.0 (temp workaround as it doesn't recognize 2.3)

**Comment by bkoski** [comment]
Thanks!  Ran into another issue on 2.3.0; submitted PR #150 as a fix.
