### ISSUE TITLE
kubeclient-1.1.1 doesn't support Kubernetes 1.2.0

### ISSUE THREAD

**Issue by KarolisL** [abonas/kubeclient#158]
Kubernetes 1.2.0 was released and it expects Content-Type header - error gets returned if it is not found, so we are unable to create/update resources. This is fixed by PR #152

Could you please release a new version?

**Comment by simon3z** [comment]
@abonas do we have anything important in the queue to wait for a new release? (I don't see any PR but maybe you have something ongoing).

**Comment by abonas** [comment]
@simon3z no, we can release just for this.
