### ISSUE TITLE
modify open_timeout

### ISSUE THREAD

**Issue by grosser** [abonas/kubeclient#163]
I want to pass in open_timeout and read_timeout since they both seem to be too big by default,
but passing them in results in `ArgumentError - unknown keyword: open_timeout:`

any idea @msufa @abonas  ?

**Comment by abonas** [comment]
@grosser could you please provide a specific code example with how you are trying to do this?
thanks!

**Comment by grosser** [comment]
```
Kubeclient::Client.new(url, 'v1', open_timeout: 2)
```

**Comment by abonas** [comment]
if I understand correctly the issue here - you are trying to pass a parameter that is not recognized/ supported by kubeclient itself at the moment, (did you see somewhere documentation of kubeclient usage with this parameter?) , so it makes sense that it doesn't work at the moment.
cc @simon3z

**Comment by grosser** [comment]
I saw that I cannot pass it in ... that's why I opened an issue :)

**Comment by abonas** [comment]
@grosser it was not clear from your issue that this is a feature request, but rather it sounded like reporting a bug.

**Comment by grosser** [comment]
ah sorry, definitely a feature request :)
(read_timeout would also be nice while we are at it ... or just all http options ...)

**Comment by abonas** [comment]
@grosser I don't think I'll have the time to get this implemented in the near future, but perhaps some other community member can pick up the glove.

**Comment by simon3z** [comment]
I am ok to add these timeouts, but remember that watches are special:

https://github.com/abonas/kubeclient/pull/24/files

In the past I had to force the `read_timeout` to `nil` in that case to prevent the connection to be dropped for inactivity.

**Comment by cben** [comment]
Done in #244 (on master & 2.4.0 via #246).
