### ISSUE TITLE
get_pod_log not finding a pod in default namespace, but cli is ...

### ISSUE THREAD

**Issue by grosser** [abonas/kubeclient#167]
`get_pod_log 'truth-service-main-role-1504526534-amcel', ''` -> error

`kubectl logs truth-service-main-role-1504526534-amcel` -> works

if I add the namespace to the get_pod_logs it works too ... but strange that it does not work without that :(

**Comment by abonas** [comment]
@grosser what kind of error do you see?

**Comment by abonas** [comment]
it is also possible that kubectl does autocompletion of the default namespace if such was not supplied, which makes it a different behavior from the REST api, which is the behavior one would get when using kubeclient.
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/logs.go
if that's the case, this is not a bug in kubeclient, but rather that the behaviors on k8s side should be aligned among REST and kubectl.
@simon3z @thockin @smarterclayton - any idea if that's indeed the case?

**Comment by cben** [comment]
By default namespace, did you mean 
- the namespace literally named `default`?
- the "current" `context.namespace` kubectl uses from kubeconfig file, as set by [`kubectl config set-context ... --namespace`](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#setting-the-namespace-preference) or `oc project`?
  The latter can now be parsed thanks to #308, you still need to pass it to all methods.

I don't think passing empty string as kubeclient namespace is supposed to work.

**Comment by grosser** [comment]
context.namespace
... passing empty string is silly anyway ... closing since I've not run into that again
