### ISSUE TITLE
set selector not supported ?

### ISSUE THREAD

**Issue by grosser** [abonas/kubeclient#168]
trying to get logs for multiple objects without success :(

```
client.get_events(field_selector: 'involvedObject.name in (my-service-secondary-role, my-service-primary-role)')
```

```
KubeException: invalid selector ... can't understand '...
```

seems to be supposed to work http://kubernetes.io/docs/user-guide/labels/ ...

**Comment by jonmoter** [comment]
FYI, I think this is an issue with Kubernetes itself, rather than the client.  See https://github.com/kubernetes/kubernetes/issues/15128, where I brought up the same issue.

**Comment by abonas** [comment]
ping @simon3z

**Comment by simon3z** [comment]
> trying to get logs for multiple objects without success :(

@grosser can you check if that works with kubectl (or with any rest-api tool). Would you paste here the request/response? Thanks.

**Comment by grosser** [comment]
querying for labels with multiple values works nicely for pods:
```
kubectl get pods -l 'deploy_group_id in (2,1)'
```

but does not seem to be supported via the cli for events ...

```
curl -s 'http://kubernetes-staging.zdsystest.com/api/v1/namespaces/mgrosser/events?fieldSelector=involvedObject.kind%20in%20%28Pod%29'
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "invalid selector: 'involvedObject.kind in (Pod)'; can't understand 'involvedObject.kind in (Pod)'",
  "code": 500
}
```

and it should work once kubernetes supports it since the passed in value is not getting messed with ...
