### ISSUE TITLE
Health check

### ISSUE THREAD

**Issue by GKTheOne** [abonas/kubeclient#170]
Support for the /healthz path?

**Comment by simon3z** [comment]
> Support for the /healthz path?

@GKTheOne that would be nice (and easy to implement). :+1: from me.

**Comment by GKTheOne** [comment]
I'll work on a PR soon(-ish) unless someone beats me to it. (Warning: I've only been doing ruby for less than a week)

**Comment by simon3z** [comment]
> I'll work on a PR soon(-ish) unless someone beats me to it. (Warning: I've only been doing ruby for less than a week)

@GKTheOne are you planning to support also `ping` and `ready`? Not sure what's the exact difference between the three (maybe they're all there just for backward compatibility?)

cc @moolitayer

**Comment by moolitayer** [comment]
@GKTheOne could you please add a link in this issue's first comment to k8s docs on relevant api bits?

**Comment by abonas** [comment]
> @GKTheOne could you please add a link in this issue's first comment to k8s docs on relevant api bits?

+1

Is this about /healthz for kubelet or containers health check?
generally speaking, a PR on health check is welcome

**Comment by GKTheOne** [comment]
I was thinking about just the apiserver /healthz endpoint. Mainly as a simple availability check.

However after a quick google turned up nothing explicit documentation-wise, and based on @simon3z and @abonas comments, I'm starting to think a) /healthz will probably be deprecated, or at least is 'private', and b) you all have bigger ideas on 'health check' 😃 

I'll do some digging this weekend and see what turns up.

@simon3z : What do you mean with `ping` and `ready`? I'm not aware of a ready endpoint, and the only ping endpoint I know of is /healthz/ping. But I still haven't looked properly at the exec-healthz code so if the answer's there then don't worry about answering. 😄 

@abonas : Can you expand on what you mean re: "health check"? I'm thinking that a /healthz kubelet check could be done by simple http(s) checks (after getting the node list via kubeclient 😄 ), and a containers health check would also be done by other methods ... but I don't know what you're thinking.

Cheers,

**Comment by simon3z** [comment]
> @simon3z : What do you mean with ping and ready? I'm not aware of a ready endpoint, and the only ping endpoint I know of is /healthz/ping. But I still haven't looked properly at the exec-healthz code so if the answer's there then don't worry about answering.

@GKTheOne:

```
# curl -k https://localhost:8443
{
  "paths": [
    ...
    "/healthz",
    "/healthz/ping",
    "/healthz/ready",
    ...
  ]
}
```

**Comment by abonas** [comment]
> @abonas : Can you expand on what you mean re: "health check"? I'm thinking that a /healthz kubelet check could be done by simple http(s) checks (after getting the node list via kubeclient  ), and a containers health check would also be done by other methods ... but I don't know what you're thinking.

@GKTheOne:
http://kubernetes.io/docs/user-guide/liveness/
although it seems that it should be self implemented already by including it in the pod definition (and making sure the status/response is read)

**Comment by GKTheOne** [comment]
Thanks for that. I'll be a bit busy for the next couple of days (2-3), but I'll get back to this then.

**Comment by GKTheOne** [comment]
n/a
