### ISSUE TITLE
Ingress support

### ISSUE THREAD

**Issue by diclophis** [abonas/kubeclient#176]
Hello,

We would like to use your library for a bespoke ruby-based ingress controller for our staging kubernetes cluster... Do you know when this library might gain support for ingress resources... and or, could you comment on how one might go about adding this resource to the library... as we may have time ourself to add the implementation.

Thank You for your time

**Comment by simon3z** [comment]
Hi @diclophis ingress requires the new group API #144. So it's tricky. 
I think @moolitayer did some analysis on how to add the group API.

If you have time, I'd say that you can start proposing a design for #144, after that the ingress support will be trivial.

**Comment by abonas** [comment]
@simon3z there's an additional user [who's interested](https://github.com/abonas/kubeclient/issues/144#issuecomment-224497707) in the group api

**Comment by diclophis** [comment]
Ok, thanks for the quick reply, we will investigate the mentioned discussions and hopefully get a fork going with some patches

**Comment by moolitayer** [comment]
@simon3z @diclophis this should be closed through #185

**Comment by simon3z** [comment]
@diclophis was this resolved by #185 ? If that's the case we could close this right?

**Comment by simon3z** [comment]
Closing for now, feel free to reopen in case this is not covered properly by #185

**Comment by diclophis** [comment]
ok great
