### ISSUE TITLE
update and delete should return proper objects

### ISSUE THREAD

**Issue by grosser** [abonas/kubeclient#196]
create and get return RecursiveObjectStruct ... update and delete return RestClient::Response ... not good ...

**Comment by simon3z** [comment]
@moolitayer can you look at this?

**Comment by moolitayer** [comment]
I agree, we should change update delete and patch. That would require a version bump as well as an 'Upgrading' Note.

**Comment by moolitayer** [comment]
https://github.com/abonas/kubeclient/pull/290
