### ISSUE TITLE
Kubeclient next: tracker of non backward compatible issues

### ISSUE THREAD

**Issue by moolitayer** [abonas/kubeclient#199]
- https://github.com/abonas/kubeclient/issues/196
- https://github.com/abonas/kubeclient/issues/198
- https://github.com/abonas/kubeclient/issues/187#issuecomment-247860068
  (basically a Readme update getting rid of all Kubeclient::X classes)

**Comment by grosser** [comment]
- remove KubeException https://github.com/abonas/kubeclient/pull/195

**Comment by cben** [comment]
#240 probably (start or stop always wrapping SSL errors — either one may break code expecting current behavior, though current behavior is inconsistent.)

**Comment by abonas** [comment]
@moolitayer have you considered tracking backward incompatible issues by labeling them directly as such? tracking them here is nice, but manual tracking is fragile and some things can slip away

**Comment by moolitayer** [comment]
@abonas sounds great. Note I cannot label stuff ATM

**Comment by abonas** [comment]
> @abonas sounds great. Note I cannot label stuff ATM

@moolitayer do you mean you cannot create new labels or you can't apply existing labels? I think you should be able to label things. Please check. I can create a new label, any preferred name?

**Comment by moolitayer** [comment]
As a non administrator (is that how it is called) I cannot assign labels. I think that why we label things using the bot in miq?

![kubeclient next tracker of non backward compatible issues issue 199 abonas kubeclient](https://cloud.githubusercontent.com/assets/3010449/24454358/3642f686-1494-11e7-95ce-f37c5d6c19c3.png)

**Comment by abonas** [comment]
@moolitayer I believe that you're right. I can create a new label and assign to the relevant issues. How would you like this label to be called?

**Comment by moolitayer** [comment]
api change ?

**Comment by abonas** [comment]
> api change ?

But backwards incompatible changes can be also non related to api change, so perhaps something more generic would be better

**Comment by moolitayer** [comment]
I sent PRs for the items mentioned here:
- https://github.com/abonas/kubeclient/pull/292
- https://github.com/abonas/kubeclient/pull/293
- https://github.com/abonas/kubeclient/pull/290

And some fixes:
- https://github.com/abonas/kubeclient/pull/288
- https://github.com/abonas/kubeclient/pull/291
- https://github.com/abonas/kubeclient/pull/294

I did not tackle #240 at this time. We need something to do for the next release ;)

**Comment by cben** [comment]
Out of date. Most already done.  We've had a couple major releases since.
We have a couple outstand backward-incompatible changes, but tracking in issue like this doesn't scale, I'll use labels if needed.
