### ISSUE TITLE
Post NetworkPolicy Annotations on Namespace

### ISSUE THREAD

**Issue by andrewkrug** [abonas/kubeclient#202]
Any examples of posting networkPolicy annotations for a namespace?

**Comment by simon3z** [comment]
cc @moolitayer

**Comment by moolitayer** [comment]
I don't have the time to write a specific example at the moment, should be something like:
```
clinet.patch_namespace('default', {'metadata' => {'annotations' => {'key' => 'value'}})
```

**Comment by andrewkrug** [comment]
@moolitayer should this work the same in theory for also apply rules to the network policy?

**Comment by andrewkrug** [comment]
So this very much does work:

isolation_policy =
    {'metadata' =>
      {'annotations' =>
        {"net.beta.kubernetes.io/network-policy"=>"{\"ingress\": {\"isolation\": \"DefaultDeny\"}}"}
      }
    }

@client.patch_namespace 'fd5ce1e9481667af26bf6a78697d8ccf4fe2d172', isolation_policy
