### ISSUE TITLE
delete with label_selector ?

### ISSUE THREAD

**Issue by grosser** [abonas/kubeclient#217]
Is there a nice way of doing this ?
... I want to delete a job and all it's pods, ideally avoiding having to find all pods and then deleting them 1-by-1 :(

**Comment by simon3z** [comment]
cc @moolitayer

**Comment by grosser** [comment]
... this could be done by exposing a free-for-all `request :delete, :pod, blob` ... something that calls rest_client under the hood and handles errors like all the other methods

**Comment by moolitayer** [comment]
We have no support that. 
@grosser is the solution you are suggesting going to call delete on all the entities one by one?

**Comment by grosser** [comment]
Ah nvm ... I though the api allowed mass deletes ... but the cli uses get + delete too ... so there might be no way of doing this :)
