### ISSUE TITLE
support of apis/extensions/v1beta1 API

### ISSUE THREAD

**Issue by hridyeshpant** [abonas/kubeclient#224]
is there any api for kind: Deployment ?
e.g 
1.kubectl get deployments // to check if deployment exists
2. kubectl apply  -f deploy.spec.yaml // to apply change to existing deployment
3. kubectl create -f deploy.spec.yaml  // create first deployment

i would like to perform above operation, but could not see any API.
Please let me know if there any other way to perform above deployment operation.

**Comment by hridyeshpant** [comment]
does it support apis/extensions/v1beta1?
looks like deployment is part of apis/extensions/v1beta1 REST API.

**Comment by simon3z** [comment]
cc @moolitayer

**Comment by moolitayer** [comment]
On first look all these should be supported, but this makes me realize we desperately need an update of the readme file. I will be available in a couple of days, @hridyeshpant in the mean time please take a look at readme under "For A Group Api:" and let us know if you have problems.

**Comment by jonmoter** [comment]
Yeah, something along the lines of:
```
client = Kubeclient::Client.new('http://localhost:8080/api/', 'extensions/v1beta1', options)
client.create_deployment deployment_spec
```

**Comment by hridyeshpant** [comment]
@moolitayer thanks for pointing "Group API", after using "Group API" , i am able to get deployment data.

yeah defiantly readme file need an update.

**Comment by simon3z** [comment]
> yeah defiantly readme file need an update.

@hridyeshpant @jonmoter @moolitayer  can anyone send a PR to update the README file?

**Comment by moolitayer** [comment]
#225 quick one since I don't have much time. @hridyeshpant you have to review now :yum:

**Comment by hridyeshpant** [comment]
@jonmoter now i am using client.create_deployment(deployment_spec) with proper api version.
Just want to check can we create deployment_spec from json file directly ?
below is my code
 Step 1 : 
@k8_group_client = Kubeclient::Client.new( 'https://api.kubetnets.dev.XYZ.com/apis',
                                               'extensions/v1beta1',
                                               {
                                                   ssl_options: @k8_config.context.ssl_options,
                                                   auth_options: @k8_config.context.auth_options
                                               }
            )
Step 2 : 
json = "{:apiVersion=>"extensions/v1beta1", :kind=>"Deployment", :metadata=>{:name=>"docker-ecs-service"}, :spec=>{:replicas=>2, :template=>{:metadata=>{:labels=>{:app=>"docker-ecs-service"}}, :spec=>{:containers=>[{:name=>"docker-ecs-service", :image=>"docker-registry.XYZ.com/library/docker-ecs-service:c15978d253f6faf8e7fea00270e9014e7b17656d", :ports=>[{:containerPort=>8080}], :env=>[{:name=>"APP_NAME", :value=>"specimen-springboot-docker-ecs-service"}, {:name=>"VERSION", :value=>"c15978d253f6faf8e7fea00270e9014e7b17656d"}], :livenessProbe=>{:httpGet=>{:path=>"/buildInfo", :port=>8080}, :initialDelaySeconds=>45, :timeoutSeconds=>10}}], :imagePullSecrets=>[{:name=>"docker-registry"}]}}}}"

Step 3 : deploy = Kubeclient::Resource.new(json) 
Step 4 : @k8_group_client.create_deployment(deploy)

getting error 
````
Users/.rvm/gems/ruby-2.3.1/gems/kubeclient-2.3.0/lib/kubeclient/common.rb:107:in `rescue in handle_exception': the server does not allow this method on the requested resource (KubeException)
	from /Users/.rvm/gems/ruby-2.3.1/gems/kubeclient-2.3.0/lib/kubeclient/common.rb:99:in `handle_exception'
	from /Users/.rvm/gems/ruby-2.3.1/gems/kubeclient-2.3.0/lib/kubeclient/common.rb:315:in `create_entity'
	from /Users/.rvm/gems/ruby-2.3.1/gems/kubeclient-2.3.0/lib/kubeclient/common.rb:191:in `block (2 levels) in define_entity_methods'```

**Comment by simon3z** [comment]
@hridyeshpant did you solve this issue or is still relevant?

**Comment by cben** [comment]
@hridyeshpant ping, is this still relevant?

If `json` holds a JSON string, in step 3 does doing `Kubeclient::Resource.new(JSON.parse(json))` instead of `Kubeclient::Resource.new(json)` work?

**Comment by cben** [comment]
[closing old inactive question issues.  feel free to reopen/open a new one.]
