### ISSUE TITLE
support of Pod Autoscaling API

### ISSUE THREAD

**Issue by hridyeshpant** [abonas/kubeclient#227]
kubectl provide Pod Autoscaling  
```kubectl autoscale deployment php-apache --cpu-percent=50 --min=1 --max=10
deployment "php-apache" autoscaled```

Do we have such API in kubeclient?

**Comment by cben** [comment]
You can use `kubectl --loglevel=11` to see the API requests and responses involved (the actual max level is more like 5, I never remember exactly so I like setting it up to 11 ;-).
I suppose it's using `/apis/autoscaling/v1/namespaces/{namespace}/horizontalpodautoscalers/{name}`?
https://kubernetes.io/docs/api-reference/v1.6/#horizontalpodautoscaler-v1-autoscaling

In theory kubeclient should now support any resource in any API group.
Can you something like `Kubeclient::Client.new('http://localhost:8080/apis', 'autoscaling/v1', options)`?

**Comment by cben** [comment]
Hi, is this still a problem?  Have you tried with an API group?

**Comment by cben** [comment]
Works for me, details below.
You're far from the first to ask how to use a non-default API group.
If you see a way to improve README so this would be clearer, please send a PR or just suggestions!

----

```bash
$ oc autoscale -n mynamespace dc/postgresql --max=1
deploymentconfig "postgresql" autoscaled
$ oc get horizontalpodautoscalers -n mynamespace
NAME         REFERENCE                     TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
postgresql   DeploymentConfig/postgresql   <unknown> / 80%   1         1         1          3m
```
Then in ruby:
```ruby
client = Kubeclient::Client.new('http://master.example.com:8443/apis', 'autoscaling/v1', options)
client.get_horizontal_pod_autoscalers
as = c.get_horizontal_pod_autoscaler("postgresql", "mynamespace")
# => #<Kubeclient::Resource kind="HorizontalPodAutoscaler", apiVersion="autoscaling/v1", metadata={:name=>"postgresql", :namespace=>"mynamespace", :selfLink=>"/apis/autoscaling/v1/namespaces/mynamespace/horizontalpodautoscalers/postgresql", :uid=>"0f950927-61c4-11e8-a369-42010a8e0002", :resourceVersion=>"55349", :creationTimestamp=>"2018-05-27T15:38:53Z", :annotations=>{:"autoscaling.alpha.kubernetes.io/conditions"=>"[{\"type\":\"AbleToScale\",\"status\":\"True\",\"lastTransitionTime\":\"2018-05-27T15:39:23Z\",\"reason\":\"SucceededGetScale\",\"message\":\"the HPA controller was able to get the target's current scale\"},{\"type\":\"ScalingActive\",\"status\":\"False\",\"lastTransitionTime\":\"2018-05-27T15:39:23Z\",\"reason\":\"FailedGetResourceMetric\",\"message\":\"the HPA was unable to compute the replica count: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services https:heapster:)\"}]"}}, spec={:scaleTargetRef=>{:kind=>"DeploymentConfig", :name=>"postgresql", :apiVersion=>"v1"}, :minReplicas=>1, :maxReplicas=>1, :targetCPUUtilizationPercentage=>90}, status={:currentReplicas=>1, :desiredReplicas=>0}>

as.spec.targetCPUUtilizationPercentage
# => 80
as.spec.targetCPUUtilizationPercentage = 90
c.update_horizontal_pod_autoscaler(as)
```

```bash
$ oc get horizontalpodautoscalers -n mynamespace
NAME         REFERENCE                     TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
postgresql   DeploymentConfig/postgresql   <unknown> / 90%   1         1         1          2m
```

Mimicking `kubectl autoscale` would require `create_horizontal_pod_autoscaler` with proper content yourself.

Note this object now also has v2beta1 version "which includes support for scaling on memory and custom metrics":
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#horizontalpodautoscaler-v1-autoscaling
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#horizontalpodautoscaler-v2beta1-autoscaling
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#api-object

**Comment by cben** [comment]
Correction, please don't do:
`Kubeclient::Client.new('http://master.example.com:8443/apis', 'autoscaling/v1', options)`
even if that makes sense and appears to work (?), but instead do:
`Kubeclient::Client.new('http://master.example.com:8443/apis/autoscaling', 'v1', options)`
This is silly (#284, #318) but this is the current documented interface.

**Comment by cben** [comment]
I believe this works and I've answered the question, feel free to reopen if still a problem.
