### ISSUE TITLE
relax requirement on recursive-open-struct

### ISSUE THREAD

**Issue by jordimassaguerpla** [abonas/kubeclient#230]
Hi,
kubeclient requires recursive-open-struct to be 1.0.0. However, there has been, on recursive-open-struct, 2 minor updates (1.0.2) which fix 2 issues:

https://github.com/aetherknight/recursive-open-struct/blob/master/CHANGELOG.md

Could you relax the requirement so that we can use kubeclient with recursive-open-struct 1.0.2? I would suggest to go for "~>1.0.0"

**Comment by simon3z** [comment]
@jordimassaguerpla I am ok with `~>1.0.0`. I think you can safely try to invest some time to send a PR for that and if @moolitayer agrees we can merge it.

**Comment by simon3z** [comment]
Closed by #231
