### ISSUE TITLE
kubect like feature for delete resources.

### ISSUE THREAD

**Issue by hridyeshpant** [abonas/kubeclient#234]
Kubectl delete -f <file_name> can delete all resource mentioned in input file.
i am creating deployment which have replica set,  the create API is working fine and creating all resources like replicaset with deployment.
But when i am using deleteAPI with same dataset, i am getting error and it seems i cant pass yml file to deleteAPI and can only pass name of the resource.  so in this cace i need to first delete the deployment and then replicaset,Is this correct, ? 

can we have same feature like kubectl have which take input data and delete all resource?

/Users//.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): https://api.kubetnets.us-west-2.dev.XYZcom/apis/extensions/v1beta1/namespaces/default/deployments/{:apiVersion=>"extensions/v1beta1", :kind=>"Deployment", :metadata=>{:name=>"springboot-docker-ecs-service", :version=>"73fd3ac505273c456254450330a9db6fc5c3a8f7", :namespace=>"default"}, :spec=>{:replicas=>2, :strategy=>{:type=>"RollingUpdate"}, :revisionHistoryLimit=>1, :selector=>{:matchLabels=>{:app=>"springboot-docker-ecs-service", :version=>"73fd3ac505273c456254450330a9db6fc5c3a8f7"}}, :template=>{:metadata=>{:labels=>{:app=>"springboot-docker-ecs-service", :version=>"73fd3ac505273c456254450330a9db6fc5c3a8f7"}}, :spec=>{:containers=>[{:name=>"springboot-docker-ecs-service", :image=>"docker-registry.com/library/specimen-springboot-docker-ecs-service:73fd3ac505273c456254450330a9db6fc5c3a8f7", :ports=>[{:containerPort=>8080}], :env=>[{"name"=>"APP_NAME", "value"=>"specimen-springboot-docker-ecs-service"},  {"name"=>"_DNS_ZONE", "value"=>"dev"}, {"name"=>"_ENVIRONMENT", "value"=>"dev"}, {"name"=>"_DEPLOYED_ENVIRONMENT", "value"=>"dev"}], :livenessProbe=>{:httpGet=>{:path=>"/buildInfo", :port=>8080}, :initialDelaySeconds=>45, :timeoutSeconds=>10}}], :imagePullSecrets=>[{:name=>"secreat"}]}}}} (URI::InvalidURIError)
	from /Users/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/uri/rfc3986_parser.rb:73:in `parse'
	from /Users/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/uri/common.rb:227:in `parse'
	from /Users//.rvm/gems/ruby-2.3.0/gems/rest-client-2.0.1/lib/restclient/request.rb:597:in `parse_url_with_auth!'
	from /Users//.rvm/gems/ruby-2.3.0/gems/rest-client-2.0.1/lib/restclient/request.rb:72:in `initialize'
	from /Users//.rvm/gems/ruby-2.3.0/gems/rest-client-2.0.1/lib/restclient/request.rb:52:in `new'
	from /Users//.rvm/gems/ruby-2.3.0/gems/rest-client-2.0.1/lib/restclient/request.rb:52:in `execute'
	from /Users//.rvm/gems/ruby-2.3.0/gems/rest-client-2.0.1/lib/restclient/resource.rb:94:in `delete'
	from /Users//.rvm/gems/ruby-2.3.0/gems/kubeclient-2.3.0/lib/kubeclient/common.rb:291:in `block in delete_entity'
	from /Users//.rvm/gems/ruby-2.3.0/gems/kubeclient-2.3.0/lib/kubeclient/common.rb:99:in `handle_exception'
	from /Users//.rvm/gems/ruby-2.3.0/gems/kubeclient-2.3.0/lib/kubeclient/common.rb:289:in `delete_entity'
	from /Users//.rvm/gems/ruby-2.3.0/gems/kubeclient-2.3.0/lib/kubeclient/common.rb:187:in `block (2 levels) in define_entity_methods'
	from /Users//.rvm/gems/ruby-2.3.0/gems/kubeclient-2.3.0/lib/kubeclient/common.rb:79:in `method_missing'
	from /Users//Documents/workspace/k8s/deployment/libs/deployment.rb:151:in `delete_deployment'
	from k8.rb:78:in `delete_deployment'

**Comment by kamerblauwlicht** [comment]
When you delete a resource  (like a `deployment`) using `kubectl` it will pass the `propagationPolicy` query to make sure all the orphaned object will be deleted too. You can't specify the `propagationPolicy` with the `kubeclient` gem yet. We have the same issue. We will create PR to fix this.

code should be something like this: 
`client.delete_deployment('name_of_your_deployment', 'namespace_of_your_deployment', propagationPolicy: 'Foreground')`

**REFERENCE:**
https://kubernetes.io/docs/api-reference/v1.6/#delete-24
about garbage colllection and values of `propagationPolicy`:
https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/

**Comment by kamerblauwlicht** [comment]
from the documentation:



`kubectl` also supports cascading deletion. To delete dependents automatically using kubectl, set --cascade to true. To orphan dependents, set --cascade to false. **The default value for --cascade is true.**

Here’s an example that orphans the dependents of a ReplicaSet:

`kubectl delete replicaset my-repset --cascade=false`

**Comment by carbonin** [comment]
Would this same issue cause a ReplicationController to be left behind when removing a DeploymentConfig in OpenShift?

**Comment by kamerblauwlicht** [comment]
@carbonin yes, this is the case. I'm going to work on this tomorrow.

**Comment by carbonin** [comment]
Great! Thanks @kamerblauwlicht

**Comment by cben** [comment]
IIUC, this has been solved by #267?  Closing, please reopen if I missed something.
