### ISSUE TITLE
Automatically detect kind and apiVersion in Resources

### ISSUE THREAD

**Issue by danajp** [abonas/kubeclient#235]
So I've found myself writing a lot of code like this lately:

```ruby
kube_url = 'https://k8s.example.com'
core_client = Kubeclient::Client.new(kube_url, 'v1', :ssl_options => some_ssl_options)
ext_client = Kubeclient::Client.new(kube_url, 'apis/extensions/v1beta1', :ssl_options => some_ssl_options)
batch_client = Kubeclient::Client.new(kube_url, 'apis/batch/v1', :ssl_options => some_ssl_options)
```

And then I have to decide which client instance to use depending on the kind of entity I'm working with. The `core` client for services, `ext` client for deployments, `batch` client for jobs, etc. It'd be nice if this worked like `kubectl apply -f some-entity.yml` where I could specify the `kind` and `apiVersion` fields in my `Kubeclient::Resource` object and have the client instance figure out which api endpoint to use:

```ruby
deployment = Kubeclient::Resource.new(
  :kind => 'Deployment',
  :apiVersion => 'extensions/v1beta1',
  # ...
)
service = Kubeclient::Resource.new(
  :kind => 'Service',
  :apiVersion => 'v1',
  # ...
)

client.create_entity(deployment)
client.create_entity(service)
```

I'm considering writing a wrapper to implement this, but I'd much rather modify kubeclient and contribute those changes upstream instead. Is this something the project would be interested in?

**Comment by simon3z** [comment]
@danajp is this a duplicate of #208 ?

**Comment by danajp** [comment]
Yep, my issue search-fu is weak. I'll close this. Thanks!
