### ISSUE TITLE
pretty-printed json wastes bandwidth

### ISSUE THREAD

**Issue by cben** [abonas/kubeclient#239]
Not sure if it was always the case, but I'm seeing k8s API default to pretty printing (newlines and indentation).
Should add `?pretty=false` in URLs to get minimized JSON.  Probably only on GET requests (?)
On deep big requests like `/pods` this can decrease response size by up to ~1.6 (e.g. 89k vs 54k).

**Comment by abonas** [comment]
good idea

**Comment by cben** [comment]
I wondered why I never see pretty-printing in productions VCRs recording kubeclient usage.
Turns out, k8s is being friendly to certain `User-Agent`s:
https://github.com/kubernetes/kubernetes/blob/8667d7c4f158/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/negotiation/negotiate.go#L102
```
	if strings.HasPrefix(userAgent, "curl") || strings.HasPrefix(userAgent, "Wget") || strings.HasPrefix(userAgent, "Mozilla/5.0") {
```
