### ISSUE TITLE
[Question] Retrieve cluster information

### ISSUE THREAD

**Issue by boeboe** [abonas/kubeclient#245]
Hi all,

I wonder if it is possible to fetch the cluster-info from the cluster the client is currently connected, in analogy with the following kubectl command?

`kubectl cluster-info`

The reason for this is that the downstream fluent-plugin-kubernetes_metadata_filter project does not enrich it's data with the cluster name, which is an important peace of information to differentiate logs within a multi-cluster setup.

REF: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/69

BR,
Bart

**Comment by moolitayer** [comment]
@boeboe do you mean this one?
```
# kubectl cluster-info
Kubernetes master is running at https://vm-48-124.eng.lab.tlv.redhat.com:8443

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

**Comment by boeboe** [comment]
Hi @moolitayer ,

Good point there... there is no such a thing as a cluster-name concept in Kubernetes. I actually ment a way to uniquely identify in which cluster a certain pod is running, being the cluster master URL in this case.

Best regards,
Bart

**Comment by moolitayer** [comment]
I see @boeboe, I'm actually dealing with the same problem.

A few interesting options for cluster identifier can be taken from the master node:
```
# oc describe node vm-48-124.eng.lab.tlv.redhat.com|grep -i id:
 Machine ID:			4bdc423c06554441a44182e398ed5990
 System UUID:			489A07B3-7877-48BC-94DD-79F1DD913E5C
 Boot ID:			d410a65c-27cd-4792-8f0b-ff9a6060aa77
ExternalID:			vm-48-124.eng.lab.tlv.redhat.com
```
I like `System UUID` best for this purpose

Anyway currently we do not support cluster-info, and strangely I can't think of a way to figure out the master node using kubeclient. There is one possible hack which is `puts client.api_endpoint` but not very reliable.

cc @simon3z @yaacov @cben (since we need to figure out this problem as well)

**Comment by boeboe** [comment]
Hi @moolitayer 

I have found an elegant way to make the downstream library mentioned also add the master_url information. This is sufficient for my use case to be able to distinguish multi-cluster log files.

REF: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/70

Thanks for your support and feed-back!
Bart

**Comment by cben** [comment]
IIUC Kubernetes may have several masters for high-availability, and also API servers != masters.
https://kubernetes.io/docs/admin/high-availability/
Don't have concrete suggestions, but maybe this helps you figure out if the API url you talk to is acceptable as the id you want...

----

FWIW here is a dump of what `cluster-info` and `cluster-info dump` access:
```
$ kubectl cluster-info -v11 |& grep -o 'GET htt[^ ]*'
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/api
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/apis
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/oapi
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/version
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/api/v1/namespaces/kube-system/services?labelSelector=kubernetes.io%2Fcluster-service%3Dtrue

> kubectl cluster-info dump -v11 |& grep -o 'GET htt[^ ]*'
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/api
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/apis
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/api/v1/nodes
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/api/v1/namespaces/kube-system/events
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/api/v1/namespaces/kube-system/replicationcontrollers
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/api/v1/namespaces/kube-system/services
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/apis/extensions/v1beta1/namespaces/kube-system/daemonsets
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/apis/extensions/v1beta1/namespaces/kube-system/deployments
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/apis/extensions/v1beta1/namespaces/kube-system/replicasets
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/api/v1/namespaces/kube-system/pods
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/api/v1/namespaces/default/events
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/api/v1/namespaces/default/replicationcontrollers
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/api/v1/namespaces/default/services
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/apis/extensions/v1beta1/namespaces/default/daemonsets
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/apis/extensions/v1beta1/namespaces/default/deployments
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/apis/extensions/v1beta1/namespaces/default/replicasets
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/api/v1/namespaces/default/pods
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/api
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/apis
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/api/v1/namespaces/default/pods/docker-registry-2-ekwis/log
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/api
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/apis
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/api/v1/namespaces/default/pods/registry-console-1-fvqp5/log
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/api
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/apis
GET https://vm-48-131.eng.lab.tlv.redhat.com:8443/api/v1/namespaces/default/pods/router-1-jt05b/log
```

**Comment by moolitayer** [comment]
@boeboe do you assume there is only one api master and that it does not change?

**Comment by boeboe** [comment]
@moolitayer

The API master have different DNS names, depending on the private data center they are residing at. This allows us to trace back from which cluster the logs are coming (we have a single ELK stack for both clusters).

**Comment by cben** [comment]
Closing as we never figured what exactly was desired, but I expect it'd be covered by `get_node` and/or #389 — GET requests on arbitrary path.
