### ISSUE TITLE
Cant pass authentication data to Client.new.

### ISSUE THREAD

**Issue by dElogics** [abonas/kubeclient#259]
If I pass -- 
`k8scli = Client.new("http://10.0.5.1/api", "v1", authentication)`
/usr/local/lib64/ruby/gems/2.2.0/gems/kubeclient-2.4.0/lib/kubeclient/common.rb:56:in `initialize_client': unknown keyword: bearer_token (ArgumentError)

Where authentication is -- 
authentication = { :bearer_token => "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" }

**Comment by cben** [comment]
For future record why this was closed: the right way to pass this is 
`Client.new("http://10.0.5.1/api", "v1", auth_options: authentication)`
