### ISSUE TITLE
Specify rest-client version

### ISSUE THREAD

**Issue by DazWorrall** [abonas/kubeclient#264]
While investigating some certificate verification errors, I discovered that we were inadvertently using rest-client v1.6.9, which doesn't support specifying custom certificate stores (this was added in [1.7.0](https://github.com/rest-client/rest-client/commit/f378ad154a6cc3a15c162552f6b1b08822885099)). Currently kubeclient [doesn't specify a rest-client version](https://github.com/abonas/kubeclient/blob/30b8285411ecfb485f7cfd816684936e32d46ba6/kubeclient.gemspec#L30), it would be helpful if it did for things like this. At least v1.7.0 is required to solve this issue, but perhaps there are other considerations which need an even newer version?

Ref: Shopify/kubernetes-deploy#157

**Comment by simon3z** [comment]
@cben can you take a look at this?

**Comment by cben** [comment]
If nobody objects, I'd like to bump to >=2.0 and drop some 1.x compatibility code around timeouts.

**Comment by simon3z** [comment]
> If nobody objects, I'd like to bump to >=2.0 and drop some 1.x compatibility code around timeouts.

@moolitayer ?

**Comment by moolitayer** [comment]
Sound good, 1.X hasn't been updated in over 2 years.
Also https://github.com/ManageIQ/manageiq/blob/master/Gemfile#L53

**Comment by simon3z** [comment]
Who is taking this?

**Comment by cben** [comment]
#269

**Comment by KnVerey** [comment]
@cben @simon3z @moolitayer Could you please release a version with this fix in it? It doesn't seem to be in 2.5.1.

**Comment by moolitayer** [comment]
> @cben @simon3z @moolitayer Could you please release a version with this fix in it? It doesn't seem to be in 2.5.1.

@simon3z or @abonas have the permissions to do that

**Comment by cben** [comment]
@KnVerey all that #269 did was bump the dependency and drop some code that tried to support old rest-client.  You can just use an existing kubeclient release and add dependency on rest-client version(s) that are safe for you.

Of course, it'll be nicer for kubeclient to specify this (hence this issue/fix).
But I'm not sure it's polite to significantly bump dependencies in minor kubeclient release — the purpose of a stable branch is minimal disruption, what if somebody uses kubeclient but is locked to say rest-client 1.9 for other reasons?
It may be safer to postpone #269 and #253 to a kubeclient 3.0 release?  If so, we ought to do a tiny patch to stable v2.x branch just requiring rest-client >=1.8 (lowest version that at least passed kubeclient tests).
@simon3z @abonas what do you prefer?  And do you have any plans for when it is time to do a 3.0?  (ref #199)

**Comment by simon3z** [comment]
> It may be safer to postpone #269 and #253 to a kubeclient 3.0 release?

+1 to release this in 3.0.

No plans for a 3.0 release yet. I know there are other PRs that we would like to merge before releasing that.

If you want you can still consume the master using the git `:ref` or `:branch` in your `Gemfile`.
