### ISSUE TITLE
Passing extra query params when deleting an entity? (i.e. a deployment)

### ISSUE THREAD

**Issue by zeroDivisible** [abonas/kubeclient#266]
Hi folks,

I had recently started using `kubeclient` as a library for abstracting communication with `Kubernetes` and I'm wondering - does this gem allow specifying extra query params when deleting an entity using Kube API?

The use case which I have is that I want to delete a deployment (`extensions/v1beta` API), but I want to pass the `propagationPolicy` param, otherwise, k8s leaves the ReplicaSet and the pods after deleting the Deployment object (basically, I want a cascade delete and need to instruct k8s to do so).

This is documented in https://kubernetes.io/docs/api-reference/v1.7/#delete-603 (`queryParameters` section).

Is this something which is supported / planned to be supported by this gem? If it's not supported yet, would incoming patches get accepted here?

**Comment by simon3z** [comment]
cc @moolitayer @cben

**Comment by cben** [comment]
Also discussed on https://github.com/abonas/kubeclient/issues/234#issuecomment-313212608 (but I think not a dup, that issue had wider goal to delete all resources from a file?).

=> #255 is open PR to support delete with query params.  Last update there was "Please hold this PR. It isn't working against 1.7.1 Kubernetes. Looks like the API doesn't know how to handle the parameters anymore."
@zeroDivisible could you see if #255 works for you / how to do it on most recent kubernetes?

**Comment by zeroDivisible** [comment]
Thanks for the updates @cben I'll give those a read and check the work carried there.

**Comment by kamerblauwlicht** [comment]
@cben @zeroDivisible @simon3z @moolitayer 

I'm going to work on the PR to make this work. Probably tomorrow there will be a fix using a body payload instead of query parameters because of the depreciation in `1.7.x`

**Comment by kamerblauwlicht** [comment]
REFERENCE: https://kubernetes.io/docs/api-reference/v1.7/#deleteoptions-v1-meta

**Comment by kamerblauwlicht** [comment]
implementation done. check my PR. 

@cben @zeroDivisible @simon3z @moolitayer

**Comment by zeroDivisible** [comment]
A bit late to the party and I didn't do a full verification, but following the changes in the README, I was able to successfully verify that the code from @kamerblauwlicht 's  PR does indeed trigger the recursive delete (at least in my scenario). 👍 from me.

**Comment by kamerblauwlicht** [comment]
@zeroDivisible good to hear. we have my code running in production ;-) and all good. hope we can merge the code soon.

**Comment by abonas** [comment]
resolved in #267
