### ISSUE TITLE
Allow passing headers per request

### ISSUE THREAD

**Issue by grosser** [abonas/kubeclient#268]
Atm I'm trying to update statefulset so I need to do this hack-around which is a bit ugly ...

```
      def deploy
        ....
        with_patch_header do
          client.patch_statefulset name, namespace, [{op: "replace", path: "/spec", value: @template.fetch(:spec)}]
        end
      end

      private
      
      def with_patch_header
        old = client.headers['Content-Type']
        client.headers['Content-Type'] = 'application/json-patch+json'
        yield
      ensure
        client.headers['Content-Type'] = old
      end
```

**Comment by moolitayer** [comment]
We have patch entity, would that serve your use case @grosser ?
```ruby
    def patch_entity(resource_name, name, patch, namespace = nil)
      ns_prefix = build_namespace_prefix(namespace)
      handle_exception do
        rest_client[ns_prefix + resource_name + "/#{name}"]
          .patch(
            patch.to_json,
            { 'Content-Type' => 'application/strategic-merge-patch+json' }.merge(@headers)
          )
      end
    end
```

**Comment by grosser** [comment]
I need to change the `Content-Type` ... I'm using patch_entity already

**Comment by moolitayer** [comment]
Oh right, so it's ` 'Content-Type' => 'application/strategic-merge-patch+json'` vs `'application/json-patch+json'`? Can you explain what is the difference? I think it was discussed in https://github.com/abonas/kubeclient/pull/161 but don't remember the distinction.

**Comment by grosser** [comment]
idk ... was following an example and the default one did not work ... have not looked any deeper :D

**Comment by cben** [comment]
doc: https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/

Are there other use cases than patch to allow direct setting of headers?
My instinct is we're clearly missing functionality in `patch_*()` and should add it, and defer the general escape hatch until proven necessary.

Current signature is `patch_foo(name, patch, namespace = nil)`.  It's awkward that we have name & namespace not adjacent :-(, and I'd like to avoid adding a 4th positional arg to it.  Cf. #312.

**Comment by stormbeta** [comment]
@cben That awkwardness with the method signature is why I didn't try to add it in a PR myself - wasn't sure what the best way to handle it would be.

It's also worth noting that some CustomResourceDefinitions may require this if they don't support strategic merge.

**Comment by cben** [comment]
Patch formats are covered by #357, more discussion there.  Seems we're all reluctant about overloading existing method, so best direction is adding new methods eg. `json_patch_*` and `merge_patch_*`.  I'm not working on it, PRs welcome.

Closing as I'm not aware of other use cases for per-request headers, but I'm opening a new issue for HTTP requests to arbitrary paths...
