### ISSUE TITLE
http gem 2.x doesn't officially support ruby 2.4

### ISSUE THREAD

**Issue by cben** [abonas/kubeclient#274]
http gem 2-x-stable branch](https://github.com/httprb/http/tree/2-x-stable, which kubeclient is on, *officially* supports MRI 2.0–2.3, no 2.4.
In principle, we should either upgrade to [http 3-x-stable](https://github.com/httprb/http/tree/3-x-stable) which supports 2.2–2.4, or contribute 2.4 support to http gem...

Kubeclient's tests do pass on MRI 2.4, but they're based on webmock, I'm not sure they prove the http gem *actually* works.

**Comment by grosser** [comment]
I'm using it on 2.4 without any issues in a lot of apps ...

**Comment by cben** [comment]
OK, it's not in their 2-x-stable README, but ruby 2.4 is tested in 2-x-stable travis, since Jan 2017 https://github.com/httprb/http/pull/386.
