### ISSUE TITLE
no get_hpa support?

### ISSUE THREAD

**Issue by waxiangzi** [abonas/kubeclient#278]
try: 
cli.get_hpa , 
return NoMethodError: undefined method `get_hpa' for #<Kubeclient::Client:0x007f982dc20570>
---
2.4.0 :022 > cli.methods.grep(/get_/)
 => [:get_bindings, :get_binding, :get_component_statuses, :get_component_status, :get_config_maps, :get_config_map, :get_endpoints, :get_endpoint, :get_events, :get_event, :get_limit_ranges, :get_limit_range, :get_namespaces, :get_namespace, :get_nodes, :get_node, :get_persistent_volume_claims, :get_persistent_volume_claim, :get_persistent_volumes, :get_persistent_volume, :get_pods, :get_pod, :get_pod_templates, :get_pod_template, :get_replication_controllers, :get_replication_controller, :get_resource_quotas, :get_resource_quota, :get_secrets, :get_secret, :get_service_accounts, :get_service_account, :get_services, :get_service, :get_entities, :get_entity, :get_pod_log]

**Comment by moolitayer** [comment]
This object recently moved, see https://github.com/kubernetes/kubernetes/pull/35782

Try to get it using the appropriate [group](https://github.com/abonas/kubeclient#usage) according to the Kubernetes version you are using
```
client = Kubeclient::Client.new('http://localhost:8080/apis/autoscaling', 'v1')
```

OR
```
client = Kubeclient::Client.new('http://localhost:8080/apis/extensions', 'v1beta1')
```

your client is for `api/v1`
