### ISSUE TITLE
Allow setting merge strategy on PATCH operations

### ISSUE THREAD

**Issue by stormbeta** [abonas/kubeclient#311]
The client is currently hard coded to use the strategic merge patch mode, which is also the Kubernetes default. Most of the time this is what you want, but not always.

For example, if you need to replace an array (e.g. Service.spec.ports[]) instead of just adding a new element to it, you need to use 'merge' instead of 'strategic'. This aligns with the `--type` parameter passed to `kubectl patch`.

For now, I'm modifying `@headers` as a workaround to override the Content-Type header:

```
client.instance_eval do
    @headers['Content-Type'] = 'application/merge-patch+json'
end
```

**Comment by cben** [comment]
closing as dup of #268, will discuss there.
