### ISSUE TITLE
Posting raw yaml or json to the api

### ISSUE THREAD

**Issue by Stono** [abonas/kubeclient#325]
Hey, 
I'm just wondering if there is any way to post the raw json or yaml kubernetes spec's that I already have via this gem?  I have some existing yaml files that I don't really want to rewrite, and just want to read them from disk and use this gem to post them off.

eg, how do I turn `resource_json = YAML.load_file('echo-server/kubernetes/service.yaml').to_h` into `Kubeclient::Resource`?

instead of the example:

```
service = Kubeclient::Resource.new
service.metadata = {}
service.metadata.name = "redis-master"
service.metadata.namespace = 'staging'
service.spec = {}
service.spec.ports = [{
  'port' => 6379,
  'targetPort' => 'redis-server'
}]
service.spec.selector = {}
service.spec.selector.name = "redis"
service.spec.selector.role = "master"
service.metadata.labels = {}
service.metadata.labels.app = 'redis'
service.metadata.labels.role = 'slave'
client.create_service(service)
```
Is this even possible?

**Comment by Stono** [comment]
Sussed it by reading https://github.com/abonas/kubeclient/issues/187

`resource = Kubeclient::Resource.new(YAML.load_file('echo-server/kubernetes/service.yaml'))

**Comment by cben** [comment]
Note that it gets trickier if apiVersion in the file may differ.
 Currently you'd need to construct a Kubeclient appropriately (there
several issues to improve this)

>
