### ISSUE TITLE
create_namespace does not work

### ISSUE THREAD

**Issue by Mahla1990** [abonas/kubeclient#336]
In ruby:2.4.0, I have a class which creates deployments, ingress and services. I also want to create a namespace in the code and I'm using the exact syntax as I see here but it keeps complaining about NoSuchMethod. This is the error I see:

`
2018-06-06 21:25:09 +0000 Exception occurred undefined method create_namespace' for #<Kubeclient::Client:0x0000000267b810>`
`E, [2018-06-06T21:25:09.158818 #7] ERROR -- #<Bunny::Session:0x2d18da8 ***, vhost=/, addresses=[***]>: Uncaught exception from consumer #<Bunny::Consumer:20049140 @channel_id=1 @queue=deployment> @consumer_tag=bunny-1528320280000-413544303139>: #<NoMethodError: undefined method create_namespace for #<Kubeclient::Client:0x0000000267b810>
`

All other methods for create and delete works fine. Was wondering why it's not working for namespace. This is the code:
`   namespace = Kubeclient::Resource.new`
  `  namespace.metadata = {}`
   ` namespace.metadata.name = ns`
    `@kube_ext_client.create_namespace namespace` (previously it was incorrectly written as create_daemon_set)

**Comment by cben** [comment]
>
> namespace = Kubeclient::Resource.new
> namespace.metadata = {}
> namespace.metadata.name = ns
> @kube_ext_client.create_daemon_set namespace
>
This is calling `create_daemon_set` - Is that the exact code you're using?
How was `@kube_ext_client` constructed - is it for some extension API group?

>

**Comment by Mahla1990** [comment]
This is how I create the client:

```
auth_options = {
      bearer_token_file: '/var/run/secrets/kubernetes.io/serviceaccount/token'
    }
    ext_client = Kubeclient::Client.new(
      "#{kube_master}/apis/extensions", 'v1beta1', auth_options: auth_options
    )
```

and that function is `create_namespace`, I saw the examples here:
[(https://github.com/abonas/kubeclient/blob/master/test/test_namespace.rb]
)
exactly like this:

```
    namespace = Kubeclient::Resource.new
    namespace.metadata = {}
    namespace.metadata.name = 'development'

    client = Kubeclient::Client.new('http://localhost:8080/api/')
    created_namespace = client.create_namespace(namespace)
```

I wrote `create_daemon_set` by mistake.

but it doesn't work. All other functions - including create_deployment and create_service - works fine. I'm using _kubeclient v2.5.1_.

**Comment by cben** [comment]
OK, can you try:

core_client = Kubeclient::Client.new(
      "#{kube_master}*/api*", '*v1*', auth_options: auth_options
)

created_namespace = core_client.create_namespace(namespace)

Namespaces are part of the "core" API group.
In the API reference, you can figure which API group you need for given
operation from:
1. URLs — it says `POST /api/v1/namespaces`
    under namespace write operations in
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#create-480
2. In the left sidebar, it says "Namespace v1 core".
   For other groups it says things such as "CronJob v2alpha1 batch" and
"DaemonSet v1beta1 extensions"...

See https://kubernetes.io/docs/reference/using-api/api-overview/ for more
details on API groups...

**Comment by Mahla1990** [comment]
You're right, it worked! Thanks a lot!!

**Comment by cben** [comment]
Glaf to haer that.
@Mahla1990 Kubeclient docs in this area are clearly lacking - we get such questions a lot...  If you see a way to improve them, please send PR or suggestions...
