### ISSUE TITLE
add watch_node support

### ISSUE THREAD

**Issue by grosser** [abonas/kubeclient#342]
this works `kubeclient.watch_entities 'nodes/foo'` so just needs an alias ... sounds good ?
@cben

**Comment by cben** [comment]
`watch_nodes` seems to work.  AFAICT `define_entity_methods` only creates watch_*plural* methods — do you mean we should add watch_*singular* methods?

**Comment by grosser** [comment]
would be nice for completeness, at first I though it's not possible until I tried on kubectl and then made the workaround

watch_nodes with name does not work:
```
irb(main):015:0> w = kubeclient.watch_nodes 'fooo'
=> #<Kubeclient::Common::WatchStream:0x000055e5d6ad6580 @uri=#<URI::HTTPS https://10.100.0.1/api/v1/watch/nodes?resourceVersion=fooo>,
```

**Comment by cben** [comment]
Hmm, it seems the "intended" way to do it now is `client.watch_nodes(name: 'foo')`.
It's not documented in README though!
And it's quite surprising for one method to do singular/plural double duty...

See #312 for overview of our current APIs wrt. `name` and `namespace` :face_with_head_bandage: 

We have #332 sketching a better replacement for `*_entity, *_entities` methods, which are not currently documented as public.
My [current proposal there](https://github.com/abonas/kubeclient/issues/332#issuecomment-400662039) uses a similar pattern where `.get` and `.watch` do double duty, depending on presence of `name` and `namespace` — I don't know if that's good or bad, feedback wanted :pray: 

---

I'm opposed to adding watch_*singular* methods like `watch_node` for clarity.  But I'd love to decide something on #332 first and align to that.

Anyway, current `name:` param should be documented in README.

**Comment by cben** [comment]
I meant I'm not opposed :)

**Comment by cben** [comment]
Much clearer docs added in #436, please review.
