### ISSUE TITLE
Ability to mutate single client to switch api group/version

### ISSUE THREAD

**Issue by kuahyeow** [abonas/kubeclient#346]
### overview of alternatives: https://github.com/abonas/kubeclient/issues/208#issuecomment-412706681

Currently in order to access api endpoints from another api group, we have instantiate a new `Client` object 

`client = Kubeclient::Client.new('http://localhost:8080/apis/rbac.authorization.k8s.io', 'v1')`

Is there a way to reset the `api_endpoint` of a pre-existing `Client` ? E.g.

```
client = Kubeclient::Client.new('http://localhost:8080/api/', "v1")
client.get_service_accounts

client.api_endpoint = 'http://localhost:8080/apis/rbac.authorization.k8s.io'
client.get_role_bindings
```

**Comment by cben** [comment]
I'll say right out that I don't like the mutation idea :worried: 
The way I see it, a client object is not just something you _need_ to perform the actions.  It's what you _pass around_ in your code to represent a specific cluster & settings.
But the way k8s apis evolve, you typical need to mix several API groups, pretty arbitrarily, in same code that works on one cluster.  (I think we all agree so far)

Now consider this code:
```
def example_function(client)
  client.list_pods
  call_sub_function(client)
  client.create_service(...)
end
```
As it happens, this code only needed one group/version (say core v1), so it never bothers to declare "now I'm switching to core v1", it just assumes it got a suitable client.
Now the problem with mutation, is that *just the act of passing same client to different code* that does need to switch groups, and then calling `example_function()` again would break it.
=> If we go this way, ALL code receiving a client should start by switching group, just to be sure :frowning_face: 

I think the implementation would not be significantly easier than a safer "union" client (you need to redo discovery on every switch, or better cache discovery results and methods from previous groups).

I'll do a summary of other directions on #208.

**Comment by kuahyeow** [comment]
Thanks @cben

I do prefer a "union" client or a client that can query the combination of all api groups. 👍 

In the absence of such a client, I was hunting for a work-around in the mean-time.

**Comment by cben** [comment]
This would also be very not thread safe (#419).
Closing this one as nobody actually preferred this option, and it won't be simpler to implement then others.  (If anyone disagrees, speak up / reopen.)
