### ISSUE TITLE
757: unexpected token at '404: Page Not Found' happens when having a 404 error 

### ISSUE THREAD

**Issue by abonas** [abonas/kubeclient#35]
757: unexpected token at '404: Page Not Found' happens when having a 404 error  happens when attempted to do Json.parse in 
raise KubeException.new(e.http_code, JSON.parse(e.response)['message'])
That happens since 404 exceptions message is of type text and not json.

**Comment by abonas** [comment]
This is caused by https://github.com/GoogleCloudPlatform/kubernetes/issues/5491

**Comment by abonas** [comment]
cc @Fryguy

**Comment by Fryguy** [comment]
I think it's ok to blow up with a JSON parse error on 404.  Alternately, you could catch that error in the handling_kube_exception method, and then translate it to a `RestClient::ResourceNotFound` error if you see  "404: Page Not Found" in the page text (or maybe RestClient has a `.http_code == 404` which you could check)

**Comment by abonas** [comment]
> I think it's ok to blow up with a JSON parse error on 404. Alternately, you could catch that error in the handling_kube_exception method, and then translate it to a RestClient::ResourceNotFound error if you see "404: Page Not Found" in the page text (or maybe RestClient has a .http_code == 404 which you could check)

the problem is that Json.parse fails, and it's hard to predict on which exception it will fail since it wasn't jsonized. For now I am aware of 404 and 500 but there might be more that we'll have to keep track of, to differentiate them from a real non valid json response that might be returned.
