### ISSUE TITLE
Watch dumps all objects when started

### ISSUE THREAD

**Issue by Stono** [abonas/kubeclient#351]
Hey, 
I'm not sure if this is a kubernetes api thing, but when I start a watch, I get an `ADDED` event for all objects in the clusters.

Is there a way to make that not happen, eg only objects changed since the watch starts?

**Comment by cben** [comment]
It's normal.  I think if you specify an initial resourceVersion, you'll only see changes since then. 

 If you want changes from now, use collection version from get_*foos*() or just specify collection

**Comment by Stono** [comment]
Hey @cben - the resourceVersion works but if the resourceVerison is outside of the retention then it errors with a 410, so the only way to get the watch up and running at that point would be to start from 0, which gives me the CREATE events! 

Feels like i'm going to have to run my own idempotency layer

**Comment by cben** [comment]
Hmm.
Ok, how about on 410 doing list and watch from the version of the returned
collection?
Or are you seeing any 410 immediately after list?

**Comment by cben** [comment]
Also, can you get desired behavior wtih kubectl or curl? (tip: kubectl --loglevel=8 or something like that dumps all http request in form of curl commands)

**Comment by Stono** [comment]
@cben that's a good shout actually, if I get a 410 back from a `watch`, do `list` and find the highest `resourceVersion` and watch from there.
