### ISSUE TITLE
Tests failing with openssl 1.1.1 (debian unstable)

### ISSUE THREAD

**Issue by pravi** [abonas/kubeclient#359]
I think this is caused by using weak keys. Debian recently moved to openssl 1.1.1 and these tests started failing. Possibly using stronger keys can fix the issue.

with kubeclient 3.0 https://ci.debian.net/data/packages/unstable/amd64/r/ruby-kubeclient/latest-autopkgtest/log.gz

and kubeclient 3.1 (below)

```
Finished in 0.452661s, 247.4259 runs/s, 985.2855 assertions/s.

  1) Failure:
KubeclientConfigTest#test_external [/<<PKGBUILDDIR>>/test/test_config.rb:98]:
Expected false to be truthy.

  2) Failure:
KubeclientConfigTest#test_allinone_nopath [/<<PKGBUILDDIR>>/test/test_config.rb:98]:
Expected false to be truthy.

  3) Failure:
KubeclientConfigTest#test_allinone [/<<PKGBUILDDIR>>/test/test_config.rb:98]:
Expected false to be truthy.

112 runs, 446 assertions, 3 failures, 0 errors, 0 skips

```

**Comment by cben** [comment]
## *Chronicle of a Failure Foretold*

OK, this was silly.  A cert used in this test has `not_after=2018-11-01 12:03:22 UTC`, so it fails past that date :hourglass: 

Working on fix...

**Comment by pravi** [comment]
@cben thanks for the fix. May be add a comment in the test about expiry date so next time it becomes easy to renew.
