### ISSUE TITLE
Any planned support for the Apps endpoints?

### ISSUE THREAD

**Issue by cschiewek** [abonas/kubeclient#369]
The Apps endpoint group (Deployments, StatefulSets, DaemonSets, and ReplicaSets) all went GA in 1.9. Are there any plans to add support for these resources?!

**Comment by cben** [comment]
Kubeclient should support all API groups. Alas, the README is quite unclear about how this works :-(
Try constructing a client with: 
```ruby
Kubeclient::Client.new('https://example.com/apis/apps', 'v1')
```
(possibly the more logical `'https://example.com/apis', 'apps/v1'` works too but that's untested and not yet guaranteed, hope to make it official later)

**Comment by cschiewek** [comment]
@cben Can you provide an example?  I've setup a apps client via
```
 context = Kubeclient::Config.read('/root/.kube/config').context('default')
 apps_endpoint = [@context.api_endpoint, 'apis/apps'].join('/')
apps_client = Kubeclient::Client.new(api_endpoint, @context.api_version, ssl_options: @context.ssl_options, auth_options: @context.auth_options)
```
And none of the list_, get_ methods work...

**Comment by cschiewek** [comment]
I got it working.  It's somewhat unfortunate that you have to make 2 clients, but so be it!  Thank you for the clarification!

**Comment by siegy22** [comment]
@cben Is this still the same as of now? I still need to make two separate kubeclient instances to be able to handle pods and deployments for example?

**Comment by cben** [comment]
Same.  Nobody is working on this currently that i know.

If you want to get into it, see issues labeled "api groups#332

**Comment by cben** [comment]
Same. Nobody is working on this currently that i know.

If you want to get into it, see issues labeled "api groups & versions".  imho the first groundwork worth doing is #332, though it's lower-level.
