### ISSUE TITLE
Automatically support GCP ApplicationDefaultCredentials

### ISSUE THREAD

**Issue by timothysmith0609** [abonas/kubeclient#392]
Continuation of #213 

It seems like a good idea to have Kubeclient automatically default to `GoogleApplicationDefaultCredentials` when the provided context's user has the `auth-provider: 'gcp'` entry. Currently, specifying application default credentials must be done explicitly. This is problematic for tools that don't know a priori what cloud provider is being targeted (e.g. [Shopify/kubernetes-deploy](https://github.com/Shopify/kubernetes-deploy)). 

Our current solution in kubernetes deploy is to subclass `Kubeclient::Config` and add our own [shim](https://github.com/Shopify/kubernetes-deploy/pull/418/files#diff-2afdf2c15d5f6b0538e430a95ad61e3bR6). I don't see a strong argument against fixing this upstream here, since the required code change is small and the default can always be overridden by the end user in `Client.new :auth_options`.

Thoughts? I know there's been a lot of discussion on this issue in the past, and `exec` support for GCP is apparently in the pipeline, though it's hard to say how far out that is.

**Comment by cben** [comment]
Generally :+1: to make config Just Work!
And avoid users having to subclass Config - I gather that's proving brittle (and it wasn't consciously designed for extension by subclassing)...

I see you wrote on https://github.com/Shopify/kubernetes-deploy/issues/406 "The ability to check for this case is hidden behind the kubeclient interface so overriding is really our only choice at the moment" -- can you elaborate? Would this fully resolve that problem?

There was some concern last time about taking on google gem dependencies which are pretty large (bigger then kubeclient's current deps iirc?).  The current "soft dependency" situation is partially compromise for that but it's not too pretty :-/

That's not a strict blocker - if we need the dependencies, so be it.

**Comment by timothysmith0609** [comment]
>The ability to check for this case is hidden behind the kubeclient interface so overriding is really our only choice at the moment" -- can you elaborate?

The issue for kubernetes-deploy is that it's agnostic about what cloud provider the end-user is targeting. For example, if we knew we would always be targetting a gcp cluster, then we could use the kubeclient ApplicationDefaultCredentials as it stands. But we need a way to find out, at runtime, which cloud provider we are dealing with. This information is encapsulated by private methods in the `Config` class (namely, `fetch_user_auth_options` or, at a higher level, `fetch_context`). The fact that `@kfcg` is private spurred the need for our subclassing and overriding strategy.

I can't find any information about when Google will begin supporting exec credentials plugins, so in the meantime it makes sense to centralize the logic in `fetch_user_auth_options`. For any tool/library that doesn't have a priori knowledge of the cluster provider, I don't see an alternative aside from having to do the subclass + override dance, which is really just further argument in favour of pushing this change upstream to here.

**Comment by cben** [comment]
> The fact that `@kfcg` is private spurred the need for our subclassing and overriding strategy.

Aha.  I don't see any reason `Config` should be opaque!
We could add say `Config#data` accessor for the underlying data.

However, `.context()` is very useful to focus on interesting part of the data, and it would be natural if it returned a passive data object with the relevant subset of data, with methods like `auth_options` to compute Kubeclient-friendly info, including obtaining exec / gcp credentials.  (Or maybe some other interface for #393)
This is not what happens currently.  `.context()` does all the work immediately and returns a passive `Context` object that _only_ contains Kubeclient-friendly info in fields like `auth_options`.  In #394 I just documented this.
I think I'll retract that documentation for now, and instead will recommend people to renew by creating a whole new `Config` object (until the new interface settled).

BTW, as kubernetes-client/ruby project has renewed activity (https://github.com/kubernetes-client/ruby/issues/20), I'm starting to think whether both gems could share config / auth logic by extracting a separate "kubeconfig" gem...

**Comment by cben** [comment]
Closing as you implemented this (#394) :tada:
Following up Config-should-not-be-opaque angle in #400 but don't expect to change that until we figure out auth renewal #393...
