### ISSUE TITLE
Scale the number of replicas in a deployment

### ISSUE THREAD

**Issue by blijblijblij** [abonas/kubeclient#398]
Is it possible to interact with the Deployment (or ReplicaSet) object to scale from that perspective? 

Scaling works via the ReplicationController object `update_replication_controller`, but I would rather use the higher abstraction Deployment object.

**Comment by cben** [comment]
It should work, you just need client for correct API group.
See https://github.com/abonas/kubeclient/issues/224#issuecomment-277537170 and #343

**Comment by cben** [comment]
something like:
```
apps_client = Kubeclient::Client.new('http://localhost:8080/apis/apps', 'v1', options)
apps_client.patch_deployment('mydeployment', {spec: {replicas: 10}})

```
If this doesn't help, try doing `RestClient.log = "stderr"` and post the output with that.

Our docs around API groups are bad — people keep asking about this...  PRs to improve the docs would be _very_ welcome.

**Comment by blijblijblij** [comment]
I get a better understanding now, yes, documentation might be better, but I'll see what I can do once played with this some more and have a better understanding, thx so far @cben

**Comment by blijblijblij** [comment]
Yes, thx for the clarrification @cben , added namespace and label selection so get some sort of nightshift scaling functionality into the cluster where things might go to 0 for internal services:

```ruby
  app_client = Kubeclient::Client.new(
    'https://kubernetes.default.svc/apis/apps',
    'v1',
    auth_options: auth_options,
    ssl_options:  ssl_options
  )

 # fetch all deployments labelled for the nightshift
  deployments = app_client.get_deployments(label_selector: 'scaling=nightly')

  deployments.each do |d|
    deployment_name = d.metadata.name
    namespace = d.metadata.namespace
    logging.info("Scaling down #{namespace}: #{deployment_name}")
    app_client.patch_deployment(deployment_name, {spec: {replicas: 0}}, namespace)
  end
```

**Comment by h0jeZvgoxFepBQ2C** [comment]
Would be great to add the default types into the readme.. like pods, deployements, services,...

**Comment by cben** [comment]
Pull requests to improve README would be _very_ welcome!  
I'm falling behind my other duties as maintainer, and besides I'm too close to the subject to feel what needs explaining...

pods & services are in core 'v1' api group, and already listed in many places in readme.  
It could be great to add several examples of creating a Client with different API group, e.g. for deployments, and to stress that you need separate Client objects to manipulate multiple groups (e.g. both pods & deployments)...

* [ ] I see somewhere under Delete section, we already have a `client.delete_deployment(...)` example, but it doesn't mention it needs anything special.
