### ISSUE TITLE
metadata.resourceVersion: Invalid value: 0x0: must be specified for an update

### ISSUE THREAD

**Issue by Stono** [abonas/kubeclient#403]
Hey, 
I'm trying to update a resource, but having no joy.

Here's the object dumped out:
```
#<Kubeclient::Resource apiVersion="networking.istio.io/v1alpha3", kind="Sidecar", metadata={:creationTimestamp=>"2019-03-26T17:22:55Z", :generation=>1, :name=>"nginx-external", :namespace=>"ingress-nginx", :resourceVersion=>"41276583", :selfLink=>"/apis/networking.istio.io/v1alpha3/namespaces/ingress-nginx/sidecars/nginx-external", :uid=>"cb4864e2-4feb-11e9-b629-42010aa4022a"}, spec=#<Kubeclient::Resource spec={:egress=>{:hosts=>["platform-alert-forwarder/*", "platform-testing/*", "ingress-nginx/oauth2-proxy", "ingress-nginx/ingress-nginx-external", "kube-system/kube-dns"]}}>>
W, [2019-03-26T17:23:01.094101 #49388]  WARN -- : [App::HandlerInvoker#rescue in invoke_handler] Handler Kubitzer::Handlers::PublicIngress failed to process create_apis_extensions_v1beta1_ingresses on extensions/v1beta1/Ingress/platform-testing-public/37204090, retry number: 0, reason: sidecars.networking.istio.io "nginx-external" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update
```

And I'm simply doing: `@api.update_sidecar(object)`?

Any ideas?

**Comment by Stono** [comment]
`create_sidecar` works fine by the way

**Comment by Stono** [comment]
Ahhh, 
Ignore me i'm an idiot.

**Comment by cben** [comment]
I don't see an obvious reason.  Can you explain for future readers?

**Comment by Stono** [comment]
I was calling `update` with a new resource, rather than taking the resource from a `get` and updating fields.  I was expecting update to do a get/merge but it wasn't.

**Comment by cben** [comment]
Aha.  Sounds similar to
https://github.com/kubernetes/kubernetes/issues/70674
I thought you can always PST / PUT  without `resourceVersion` but
apparently it depends on kind now :-(

`update_` is PUT, a complete replacement.
If you only want to change some fields, try the `*patch_` methods (without
passing resourceVersion) - theae do atomic merge on server, I expect that'll
always work.

If you do want replacement:
If you're able to `create_` without resourceVersion, maybe you can omit it
from `update_` too (?)
if not, you'll have to do `get_` and then `update_` with same
resourceVersion, and retry in case of a race (if somebody else updated the
object between GET and PUT, the version won't match, it's like rebasing to
solve a merge conflict)
