### ISSUE TITLE
delete pod gives Kubeclient::ResourceNotFoundError HTTP status code 404

### ISSUE THREAD

**Issue by fadyZohdy** [abonas/kubeclient#405]
kubernetes cluster 1.11.7
kubeclient version 4.3.0
when i try to delete a pod as follows
`kube_client.delete_pod "<pod_name>"`
it gives me this error
`Kubeclient::ResourceNotFoundError (HTTP status code 404, the server could not find the requested resource for DELETE https://api.kube.com/api/v1/pods/<pod_name>)`
i can get pods and nodes just fine with the same client
am i missing something ?
and thank you guys for the amazing work you are doing 🙏

**Comment by cben** [comment]
Aha, pods are namespaced, so you must specify a namespace.

### Could error message be better?
Currently kubeclient trusts you to know which resources are namespaced and which are global.
It does get `namespaced` bool for each resource in discovery info, so could in theory use that to provide a better message.
Though I think this message is largely coming from the server:
```
# peeking at raw response is a bit hard as RestClient raises exception, 
# but caught exception object has `.response` attr.
[3] pry(main)> begin
[3] pry(main)*   client.delete_pod 'foo'  
[3] pry(main)* rescue => e  
[3] pry(main)*   puts e.response.body  
[3] pry(main)* end  
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"the server could not find the requested resource","reason":"NotFound","details":{},"code":404}
```
so it'd be more productive to improve the message on the server to tell you this kind of resources is namespaced, vs correct url structure specific name not found...

**Comment by cben** [comment]
`get_pods` worked for you because it supports both modes: list one namespace, or if not specified list all namespaces.
And `get_nodes` worked simply because nodes are not namespaced.

So here you want: 
```
client.delete_pod('name', 'namespace')
```
(see #312 for cheat-sheet of how to specify namespace to various methods, currently quite inconsistent)

**Comment by cben** [comment]
Closing but feel free to reopen
