### ISSUE TITLE
AmazonEksCredentials sometimes generates a base64 encoding that IAM auth rejects

### ISSUE THREAD

**Issue by mastamark** [abonas/kubeclient#424]
Sometimes a base64 encoding of the presigned url has 1 equals signs as padding, and current logic (`.chomp('==')`) does not handle that case.

(The IAM auth of the eks cluster then spits out a message about an invalid base64 encoding)

PR https://github.com/abonas/kubeclient/pull/423 will remove either 1 or 2 equals signs using `.sub(/=(.*)?/,'')`.

**Comment by cben** [comment]
Closed by #423
