### ISSUE TITLE
NoMethodError: undefined method `watch_pods'

### ISSUE THREAD

**Issue by mecampbellsoup** [abonas/kubeclient#443]
Hey guys -

What is the relationship between the `get_`, `watch_`, etc. methods, and my k8s cluster?

For example, why can I use my kubeclient to `watch_workflows` in this example but not `watch_pods` (isn't everything a pod in k8s)?

```ruby
[2] pry(main)> client.watch_workflows
=> #<Kubeclient::Common::WatchStream:0x0000560985209380
 @formatter=#<Proc:0x00005609852093d0@/usr/local/bundle/gems/kubeclient-4.6.0/lib/kubeclient/common.rb:314 (lambda)>,
 @http_client=nil,
 @http_options=
  {:basic_auth_user=>nil,
   :basic_auth_password=>nil,
   :headers=>{},
   :http_proxy_uri=>nil,
   :http_max_redirects=>10,
   :ssl=>
    {:ca_file=>nil,
     :cert=>
      #<OpenSSL::X509::Certificate
       subject=#<OpenSSL::X509::Name CN=kubernetes-admin,O=system:masters>,
       issuer=#<OpenSSL::X509::Name CN=kubernetes>,
       serial=#<OpenSSL::BN 1963704415468317551>,
       not_before=2019-09-09 21:12:06 UTC,
       not_after=2020-09-08 21:12:07 UTC>,
     :cert_store=>
      #<OpenSSL::X509::Store:0x0000560984f5f1e8
       @chain=nil,
       @error=nil,
       @error_string=nil,
       @time=nil,
       @verify_callback=nil>,
     :key=>#<OpenSSL::PKey::RSA:0x0000560984f5f170>,
     :verify_mode=>1},
   :socket_class=>nil,
   :ssl_socket_class=>nil},
 @uri=#<URI::HTTPS https://10.134.10.13:6443/apis/argoproj.io/v1alpha1/watch/workflows>>
[3] pry(main)> client.watch_pods
NoMethodError: undefined method `watch_pods' for #<Kubeclient::Client:0x0000560984f5f0a8>
Did you mean?  watch_pod_log
from /usr/local/bundle/gems/kubeclient-4.6.0/lib/kubeclient/common.rb:103:in `method_missing'
```

**Comment by cben** [comment]
According to the URI, looks like you created a Client for `argoproj.io/v1alpha1` API group (which I guess is from https://github.com/argoproj/argo).

Pods are in the core `v1` group.
(See https://kubernetes.io/docs/concepts/overview/kubernetes-api/#api-groups)

Currently you need a separate `Client` instance for each API group you use.  Each one defines methods only for kinds that it discovers under that group.

Let me know if this helped.

**Comment by mecampbellsoup** [comment]
Super helpful indeed - thanks @cben, much obliged.

**Comment by cben** [comment]
> isn't everything a pod in k8s?

No.  Kubernetes defines many object types (kinds), some representing stuff involved in actually running applications (like nodes, pods, services, ingresses, volumes...), some being abstract k8s concepts like service accounts and RBAC permissions...

It also allows defining any number of "custom resources".  The Argo workflows are such custom resources. They don't have any inherent meaning to k8s itself, but there is typically a program - usually called "controller" or "operator" - that watches/validates/updates such resources, and does something in response to them.

What you maybe meant is that many object kinds representing different ways to run something - e.g. Deployment, ReplicaSet, DaemonSet, Job, CronJob, and apparently Argo Workflow, ultimately result in creation of Pod objects (which results in some node running a pod).
That's true, but it's not manifest at the API layer kubeclient talks to.  To the API, each kind is separate.  (It doesn't know there are controller loops whose _behavior_ is to take object X and create object Y.)
