### ISSUE TITLE
Modify request Content-Type header for POST/PATCH/etc.

### ISSUE THREAD

**Issue by mecampbellsoup** [abonas/kubeclient#445]
I'm currently having an issue with patching an Argo workflow (but I assume this issue applies to all updates of k8s resources in general).

How can I set a request header on this request to modify the `Content-Type` to one indicated in the error message?

```ruby
From: /concierge-render/app/lib/argo/argo.rb @ line 143 Argo::Argo.terminate_workflow:

    134: def self.terminate_workflow(id)
    135:   patch = {
    136:     spec: {
    137:       shutdown: 'Terminate',
    138:     }
    139:   }.to_json
    140:   begin
    141:     client.patch_workflow(id, patch, namespace)
    142:   rescue Exception => e
 => 143:     binding.pry
    144:   end
    145: end

[1] pry(Argo::Argo)> e
=> #<Kubeclient::HttpError: HTTP status code 415, the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json, application/apply-patch+yaml for PATCH https://kube-api.chi.atlanticcrypto.com:6443/apis/argoproj.io/v1alpha1/namespaces/tenant-concierge/workflows/render-nwg97>
[2] pry(Argo::Argo)> id
=> "render-nwg97"
[3] pry(Argo::Argo)> patch.to_json
=> "{\"spec\":{\"shutdown\":\"Terminate\"}}"
[4] pry(Argo::Argo)> namespace
=> "tenant-concierge"
```

**Comment by cben** [comment]
I think I know what's going on.  
Kubernetes supports several patch formats — https://kubernetes.io/docs/tasks/manage-kubernetes-objects/update-api-object-kubectl-patch/

- `.patch_*()` methods use "strategic-merge-patch" format.
  However, Argo's Workflow kind is implemented by a Custom Resource Definition, and CRDs [do not and will not support it](https://github.com/kubernetes/kubernetes/issues/58414).

- => Try `.merge_patch_workflow()` (which sends `application/merge-patch+json`) or `.json_patch_workflow()` (which sends `application/json-patch+json`).
  Note the content of the patch differs, especially for JSON patch, see above doc page.

- `application/apply-patch+yaml` refers to [Server-Side Apply](https://kubernetes.io/docs/reference/using-api/api-concepts/#server-side-apply), which kubeclient doesn't support yet #358.

**Comment by mecampbellsoup** [comment]
@cben you are exactly right, see: https://github.com/argoproj/argo/issues/3221#event-3435916946
