### ISSUE TITLE
How to create a deployment

### ISSUE THREAD

**Issue by tle-huu** [abonas/kubeclient#449]
Hi,

I am having a hard time trying to create deployments.

Since the create_deployment method does not seem to exist anymore, I am using create_entity this way:

```
deployment = {
  apiVersion: "apps/v1",
  kind: "Deployment",
  metadata: {
    name: "test",
    namespace: "default",
    labels: {
      app: "testing-test"
    }
  },
  spec: {
    replicas: 3,
    selector: {
      matchLabels: {
        app: "testing-test"
      }
    },
    template: {
      metadata: {
        labels: {
          app: "testing-test"
        }
      },
      spec: {
        containers: [
          {
            name: "oui",
            image: "my_app:v1",
            ports: [
              {
                containerPort: 80
              }
            ]
          }
        ]
      }
    }
  }
}

deploy = Kubeclient::Resource.new(deployment)
client.create_entity("Deployment", "deployments", deploy)
```

I am getting a 404 RestClient not found and ```the server could not find the requested resource (Kubeclient::ResourceNotFoundError)```

Is there a simple way to create deployments ?

**Comment by cben** [comment]
How are you creating the `client` object?  The lack of `create_deployment` method suggests it's a client for the wrong API group.

**Comment by tle-huu** [comment]
I mean, git grepping the repo shows no create_deployment method.

here is how I am creating the client:
```
	config = Kubeclient::Config.read(ENV['KUBECONFIG'])
	context = config.context
	ssl_options = context.ssl_options
	auth_options = context.auth_options

	KUBE_CLIENT = Kubeclient::Client.new(
	    context.api_endpoint, 'v1',
	    ssl_options: ssl_options, auth_options: auth_options
	)
```

**Comment by cben** [comment]
> I mean, git grepping the repo shows no `create_deployment` method.

It wouldn't — kubeclient defines methods on the fly (using `define_singleton_method`) based on discovery info from k8s.

Each `Client` object covers only 1 api group.
By default, a Client is configured for a the core api group (`apiVersion: "v1"`), which has things like `node` & `pod`.
For deployments, you need a Client for `apiVersion: apps/v1` group .

Try something like this:
```ruby
# assuming you still need a core group client for other stuff...
core_client = Kubeclient::Client.new(
	    context.api_endpoint, 'v1',
	    ssl_options: ssl_options, auth_options: auth_options
	)
apps_client = Kubeclient::Client.new(
	    context.api_endpoint + '/apis/apps', 'v1',
	    ssl_options: ssl_options, auth_options: auth_options
	)

apps_client.create_deployment(...)
```

The README could be improved about this.  PR very welcome.
