### ISSUE TITLE
support to group API

### ISSUE THREAD

**Issue by glasswalk3r** [abonas/kubeclient#463]
Hello there,

I've being looking for a way to list/describe resources like ingresses, hpa and deployments, but can't find a way to do that using `kubeclient`.

I found some older issues mentioned what seems to be a confirmation that such API Groups are supported by this project, but couldn't find any example and/or documentation mentioning how to do that:

- #350 
- #176 
- #278 
- #227 

I even gave a try using `pry`, noticed that some methods are defined at runtime (after sending a `get_pods`, for example), but nothing related those API Groups that I already mentioned.

Am I missing something here, or this support is not complete at the moment?

That's the code I'm using for testing:

```ruby
config = Kubeclient::Config.read("#{ENV['HOME']}/.kube/config")
context = config.context

client = Kubeclient::Client.new(
  context.api_endpoint,
  'v1',
  ssl_options: context.ssl_options,
  auth_options: context.auth_options
)
```

Thanks in advance,

Alceu

**Comment by glasswalk3r** [comment]
After reviewing more issues like that and some debugging configuration for `restclient` (`RESTCLIENT_LOG=stdout bundle exec ruby test.rb`), I could get a working example:

```ruby
# frozen_string_literal: true

require 'kubeclient'

def k8s_client
  config = Kubeclient::Config.read("#{ENV['HOME']}/.kube/config")
  context = config.context
  puts context.api_endpoint

  Kubeclient::Client.new(
    "#{context.api_endpoint}/apis/extensions",
    'v1beta1',
    ssl_options: context.ssl_options,
    auth_options: context.auth_options
  )
end

client = k8s_client
puts client.get_ingresses(namespace: 'qa')
```

Does that mean that I need to create a client instance to be able to execute queries with the "old" API and then create a new instance to query the "v1beta1"?

Or is there any shortcut for configure that on the fly (I saw that the client instance has an `api` Hash, not sure if it's advisable to change any in there).

**Comment by cben** [comment]
Yes, you need a separate client object per API group that you want to use.

See https://github.com/abonas/kubeclient/issues/208#issuecomment-412706681 for overview of various proposals we have to improve this in the future.

BTW, extensions v1beta1 is deprecated:
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ lists new API groups that replace it, with version ranges when you can/must switch.
