### ISSUE TITLE
Query on kubeclient gem default certificates

### ISSUE THREAD

**Issue by chaitrahegde115** [abonas/kubeclient#499]
Hi,
  I have installed kubeclient gem in td-agent. This gem has installed default certificates in test/config/ folder. So I wanted to know what is the use of these certificates and are these certificates used when using this gem?

**Comment by cben** [comment]
No, they were only used by unit tests, not at runtime.

That particular test is currently disabled, the certs expired and i havent
yet figured out how to generate new ones - im not sure what scenario that
test was supposed to test.
30 апр. 2021 г. 3:34 PM пользователь "chaitrahegde115" <
***@***.***> написал:

**Comment by chaitrahegde115** [comment]
Ok. Thank you
