### ISSUE TITLE
GET a single entity must include namespace in the url

### ISSUE THREAD

**Issue by abonas** [abonas/kubeclient#51]
This doesn't work:
http://localhost:8080/api/v1beta3/services/kubernetes

This works:
http://localhost:8080/api/v1beta3/namespaces/default/services/kubernetes

The above is NOT relevant for nodes that are continued to be retrieved without namespace in the url.

**Comment by abonas** [comment]
not relevant for nodes, namespaces

**Comment by stephenjlevy** [comment]
Any estimate for when this might be implemented?  Only the default namespace can be used with the v1beta3 api right now because of this.  I can potentially work on it if needed.

**Comment by abonas** [comment]
@stephenjlevy there's no day like today to add this :)

**Comment by stephenjlevy** [comment]
Awesome! I still think it's missing namespace support for get_entities though.

**Comment by abonas** [comment]
> Awesome! I still think it's missing namespace support for get_entities though
@stephenjlevy 
Yes, this particular issue is for a single GET. 
get_entities should be handled separately.
imo get_entities is lower priority, because doing a GET without namespaces on get_entities works, while on a single GET it doesn't.
BTW, if you could elaborate on your use cases with kubeclient? 
it will be interesting to learn how the gem is used.

**Comment by stephenjlevy** [comment]
@abonas Working on an automated deployment layer for kubernetes and other cluster managers, so need the ability to manage the lifecycle of all entities in a kubernetes cluster.

**Comment by abonas** [comment]
> @abonas Working on an automated deployment layer for kubernetes and other cluster managers, so need the ability to manage the lifecycle of all entities in a kubernetes cluster.

great, thanks. is it open source?

**Comment by stephenjlevy** [comment]
> @abonas Working on an automated deployment layer for kubernetes and other cluster managers, so need the ability to manage the lifecycle of all entities in a kubernetes cluster.
> great, thanks. is it open source?

It's for in-house use at the moment, although we may be able to open source part of it.
