### ISSUE TITLE
How to check if CRD exists?

### ISSUE THREAD

**Issue by zulh-civo** [abonas/kubeclient#511]
Is there any `kubectl api-resources | grep my-crd` equivalent method that I can call from my Ruby code via this gem?

I want to check if my specific CRD is exist or not and do something with it.

**Comment by cben** [comment]
There are 2 mechanisms:

1. To get ALL apis supported by server (builtin + api aggregation + CRDs), clients can do api discovery.
  See example data:
  https://cben.github.io/kubernetes-discovery-samples/k0s-v1.21.0-k0s.0/
  https://cben.github.io/kubernetes-discovery-samples/k0s-v1.21.0-k0s.0/apis/
  https://cben.github.io/kubernetes-discovery-samples/k0s-v1.21.0-k0s.0/apis/batch/
  https://cben.github.io/kubernetes-discovery-samples/k0s-v1.21.0-k0s.0/apis/batch/v1/
  kubecliet does it internally (see code for `load_entities`), for 1 api group per Client, but doesn't expose the results directly.
  - if you create a client for the specific api group of the CRD you expect, you can use `client.respond_to?` to probe methods dynamically created by kubeclient.  (We have `respond_to_missing?` hook so this will perform discovery if not done yet)
  - you could use `client.faraday_client` and then perform any discovery requests by yourself...

2. CRDs are defined by regular resources (`kubectl get crd`)!
  apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
  So for them, something like this should work (untested):
    ```
    ext_client = kubeclient::Client.new("http://#{HOST}/apis/apiextensions.k8s.io", 'v1')
    ext_client.get_custom_resource_definition('foo')
    ext_client.get_custom_resource_definitions
    ```

I'd recommend `.respond_to?` as the higher-level Ruby approach, that doesn't care _how_ the resource is implemented in kubernetes, only whether it exists.  But the 2nd method may be natural if you're doing it in CRD-specific context anyway, e.g. to decide whether to `.create_custom_resource_definition(...)`.

**Comment by zulh-civo** [comment]
Thank you
