### ISSUE TITLE
client is created although ssl certificate is expired

### ISSUE THREAD

**Issue by yifatmakias** [abonas/kubeclient#514]
Hi,
I tried using this code to create a kubeclinet:
cert_store = OpenSSL::X509::Store.new
cert_store.add_cert(OpenSSL::X509::Certificate.new(ca_cert_data))
ssl_options = {
  cert_store: cert_store,
  verify_ssl: OpenSSL::SSL::VERIFY_PEER
}
client = Kubeclient::Client.new(
  'https://localhost:8443/api', 'v1', ssl_options: ssl_options
)

with an expired ssl certificate and it worked. should it be like this?

**Comment by cben** [comment]
Maybe :-) 🤔 

Kubeclient cant generally tell whether a given cert will be valid and authorized _for a given cluster_.  Creating a `client` object does not yet make any requests.

**Comment by cben** [comment]
I'll add that you can do `client.discover` to force a request (that would anyway be done before later requests, so not a waste).
However that accesses paths that are open without auth on many k8s versions, so not sure it'll reject the request when client cert is invalid.

@yifatmakias @masayag can we close this?
If you believe there is value in kubeclient checking timestamps, PR welcome.

**Comment by masayag** [comment]
> I'll add that you can do `client.discover` to force a request (that would anyway be done before later requests, so not a waste). However that accesses paths that are open without auth on many k8s versions, so not sure it'll reject the request when client cert is invalid.
> 
> @yifatmakias @masayag can we close this? If you believe there is value in kubeclient checking timestamps, PR welcome.

Yes, you can.
