### ISSUE TITLE
Using Bearer token impacts any RestClient instance

### ISSUE THREAD

**Issue by oschreib** [abonas/kubeclient#84]
As bearer token is using RestClient.add_before_execution_proc to inject the "authorization" HTTP header, it can affect any other RestClient instance created.
For instance, having two separate KubeClient instances, with separate bearer token inside each one, will result in a conflict, as the last bearer token will be injected to both of the objects.

p.s  - we might want to get https://github.com/rest-client/rest-client/pull/137 merged, which will be perfect for that exact matter.

**Comment by oschreib** [comment]
cc @simon3z  @abonas

**Comment by jimmidyson** [comment]
Alternatively switch to something like HTTParty as a client which seems much nicer for using with multiple client instances?
