### ISSUE TITLE
Move ssl_options & auth options into constructor

### ISSUE THREAD

**Issue by jimmidyson** [abonas/kubeclient#91]

**Comment by abonas** [comment]
@jimmidyson, please make sure the readme is aligned with this change, I'd like to release a new gem ver. with latest commits. thanks!

**Comment by jimmidyson** [comment]
@abonas I think it is aligned with this change, isn't it?

**Comment by abonas** [comment]
> @abonas I think it is aligned with this change, isn't it?

I'm not saying it's not :) , I just wanted to make sure it fully updated before releasing a new version, as once a gem is released, if it's unusable, it's hard to get rid of it (you need to yank it on rubygems, but can't reupload it unless you bump version again)

**Comment by simon3z** [comment]
@jimmidyson @abonas thanks for this fix (cc @oschreib ), we actually require this ASAP (let's wait for Mooli's changes and then let's build a new gem)

**Comment by abonas** [comment]
> @jimmidyson @abonas thanks for this fix (cc @oschreib ), we actually require this ASAP (let's wait for Mooli's changes and then let's build a new gem)

@simon3z , this was released as part of 0.2.0 so to use it, either 0.2.0 or 0.3.0 can be taken. 
I am probably missing something in your comment above :)
https://github.com/abonas/kubeclient/compare/v0.1.17...v0.2.0

**Comment by simon3z** [comment]
@abonas apparently this commit also carries a fix (that shouldn't have been part of the patch):

https://github.com/abonas/kubeclient/commit/5cf2c3abdff01b63a52b6a817beb17fe9fe1d79e#diff-78cbcd17c7ae3f02081ec1ce253bb73bR43

cc @jimmidyson 

Now we find ourselves in a situation where we can't bump from `v0.1.17` (and fix the `to_s` part in ManageIQ) without carrying in also all the `ssl_options` changes. Which is something that Mooli is working on.

**Comment by simon3z** [comment]
@abonas so what I meant is to wait for @moolitayer's patch and build right away because we're not only introducing quota and limits but also fixing an important issue. (This is the effect of not having a stable branch, which anyway is too early to have).

**Comment by jimmidyson** [comment]
@simon3z Moving to `ssl_options` should be a case of just moving the previous `ssl_options` into your `.new` call?

**Comment by simon3z** [comment]
@jimmidyson yes I wanted to fix the `to_s` part without having to move to the new API. It will be easier in the future when we'll have a stable branch.

**Comment by simon3z** [comment]
@jimmidyson only problem here was the lack of awareness of an important issue that should be filed/resolved separately.

**Comment by jimmidyson** [comment]
@simon3z I'd personally just be happy that the fix is there :)
