### ISSUE TITLE
gem release with changes from commit #91 ?

### ISSUE THREAD

**Issue by maratoid** [abonas/kubeclient#99]
Any chance you could cut a release with changes from #91? As it is right now, none of the auth and ssl option passing described in the README works in the latest release.

Thanks!

**Comment by abonas** [comment]
@maratoid, sure, can you please provide some more details - which options are you trying to use and how / which error do you get? thanks!

**Comment by jimmidyson** [comment]
@maratoid You're right - the README is for the current master & so options detailed there won't work until the next release.

**Comment by abonas** [comment]
@maratoid, @jimmidyson new gem 0.2.0 was now released.

**Comment by maratoid** [comment]
Thanks!
